package org.openelisglobal.microbiology.valueholder;

public enum MicroCaseActivityType {
    CASE_CREATED, STAGE_CHANGED, ISOLATE_CREATED, ISOLATE_UPDATED, AST_RUN_CREATED, AST_READING_RECORDED,
    AST_READING_OVERRIDDEN, AST_REVIEWED, CRITICAL_COMMUNICATION_LOGGED, CRITICAL_COMMUNICATION_ACKNOWLEDGED,
    PRELIMINARY_REPORT_RELEASED, FINAL_REPORT_RELEASED
}
