package org.openelisglobal.qaevent.service;

import java.sql.Date;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import org.openelisglobal.common.log.LogEvent;
import org.openelisglobal.common.service.AuditableBaseObjectServiceImpl;
import org.openelisglobal.qaevent.dao.NCEventDAO;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class NCEventServiceImpl extends AuditableBaseObjectServiceImpl<NcEvent, Integer> implements NCEventService {

    private static final String STATUS_PENDING = "Pending";
    private static final String ACTIVITY_AUTO_CREATED = "AUTO_CREATED";

    @Autowired
    protected NCEventDAO baseObjectDAO;

    @Autowired
    private NceNumberGeneratorService nceNumberGeneratorService;
    @Autowired
    private NceHistoryService nceHistoryService;

    public NCEventServiceImpl() {
        super(NcEvent.class);
        this.auditTrailLog = true;
    }

    @Override
    @Transactional(readOnly = true)
    public List<NcEvent> findByNCENumberOrLabOrderId(String nceNumber, String labOrderId) {
        return baseObjectDAO.findByNCENumberOrLabOrderId(nceNumber, labOrderId);
    }

    // Joins whatever transaction the trigger opened rather than starting its own:
    // each trigger service runs this in a REQUIRES_NEW transaction of its own so
    // an NCE failure cannot poison the work that raised it.
    @Override
    @Transactional
    public NcEvent createAutoGenerated(NcEvent nce, String historyNote, Consumer<NcEvent> afterCreate) {
        NcEvent existing = getMatch(
                Map.of("triggerSourceType", nce.getTriggerSourceType(), "triggerSourceId", nce.getTriggerSourceId()))
                .orElse(null);
        if (existing != null) {
            return existing;
        }

        nce.setNceNumber(nceNumberGeneratorService.generateNceNumber());
        nce.setStatus(STATUS_PENDING);
        nce.setAutoGenerated(Boolean.TRUE);
        nce.setReportDate(new Date(System.currentTimeMillis()));

        NcEvent saved = save(nce);
        if (afterCreate != null) {
            afterCreate.accept(saved);
        }
        nceHistoryService.logActivity(saved.getId(), ACTIVITY_AUTO_CREATED, historyNote, null, null,
                historyUserId(saved.getSysUserId()));

        LogEvent.logInfo(this.getClass().getSimpleName(), "createAutoGenerated", "Created " + saved.getNceNumber()
                + " from " + saved.getTriggerSourceType() + " " + saved.getTriggerSourceId());
        return saved;
    }

    /** The history entry wants a numeric user; a non-numeric one falls back too. */
    private Integer historyUserId(String sysUserId) {
        try {
            return Integer.valueOf(sysUserId);
        } catch (NumberFormatException e) {
            return Integer.valueOf(SYSTEM_USER_ID);
        }
    }

    @Override
    @Transactional(readOnly = true)
    public NcEvent findByTriggerSource(String triggerSourceType, String triggerSourceId) {
        return baseObjectDAO.findByTriggerSource(triggerSourceType, triggerSourceId);
    }

    @Override
    protected NCEventDAO getBaseObjectDAO() {
        return baseObjectDAO;
    }
}
