package org.openelisglobal.qaevent.service;

import java.util.List;
import java.util.function.Consumer;
import org.openelisglobal.common.service.BaseObjectService;
import org.openelisglobal.qaevent.valueholder.NcEvent;

public interface NCEventService extends BaseObjectService<NcEvent, Integer> {

    /**
     * Stands in for the operator on anything a system trigger raises with nobody
     * logged in (a scheduled evaluation, a background hook). The admin user holds
     * the place until a dedicated system account exists.
     */
    String SYSTEM_USER_ID = "1";

    List<NcEvent> findByNCENumberOrLabOrderId(String nceNumber, String labOrderId);

    /**
     * Saves the non-conformity a system trigger raises, or returns the one that
     * already exists for the same trigger. At most one NCE exists per trigger
     * source (uq_nc_event_trigger_source), so a repeated trigger reads back the
     * first one instead of duplicating it.
     *
     * <p>
     * The caller sets the fields that vary by trigger — at minimum the trigger
     * source type and id, the severity, the reporting user, the title and the
     * description. This fills in the generated number, the pending status, the
     * auto-generated flag and the report date, then writes the AUTO_CREATED history
     * entry.
     *
     * @param historyNote what the AUTO_CREATED history entry records
     * @param afterCreate work needing the saved id, such as linking affected
     *                    samples; may be null, and is skipped entirely when an NCE
     *                    already existed for the trigger
     */
    NcEvent createAutoGenerated(NcEvent nce, String historyNote, Consumer<NcEvent> afterCreate);
}
