#Faclity FHIR server
#org.openelisglobal.facilitylist.fhirstore = https://hub.openelisci.org:5000/gofr/exemple4
#org.openelisglobal.facilitylist.authurl= https://hub.openelisci.org:5000/gofr/token
#org.openelisglobal.facilitylist.username= root@gofr.org
#org.openelisglobal.facilitylist.password= gofr
#org.openelisglobal.facilitylist.auth= token
facilitylist.schedule.fixedRate=864000000
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Enable FHIR integration in production
org.openelisglobal.fhir.integration.enabled=true
server.ssl.key-password=testtest
# SSL Config
server.ssl.key-store=file:/ssl/lf.keystore
server.ssl.key-store-password=testtest
server.ssl.trust-store=file:/ssl/lf.truststore
server.ssl.trust-store-password=testtest
spring.jpa.properties.hibernate.format_sql=true
#Hibernate Config
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
vapid.private.key=FVONpka44MuWq6U8l3X4HY1hAfWM1v1IQB698gsS0KQ
vapid.public.key=BJDIyXHWK_o9fYNwD3fUie2Ed04-yx5fxz9-GUT1c0QhfdDiGMvVbJwvB_On3XapXqIRR471uh7Snw3bfPt9niw