# HT LNSP Form Fields Configuration
# Overrides for LNSP_HAITI domain
# Format: FieldName=inUse,required,labelKey,label

StNumber=false,false
AKA=false,false
MothersName=false,false
PatientType=false,false
InsuranceNumber=false,false
OrgLocalAbrev=false,false
InlineOrganizationTypes=true,false
Occupation=false,false
ADDRESS_DEPARTMENT=true,false
MotherInitial=true,false
ResultsReferral=true,false
ValueHozSpaceOnResults=true,false
InitialSampleCondition=true,false
OrganizationMultiUnit=false,false
OrganizationOrgId=false,false
RequesterSiteList=true,false
ADDRESS_CITY=false,false
PatientRequired=true,false
SampleCondition=false,false
NON_CONFORMITY_SITE_LIST=true,false
PatientNameRequired=false,false
SampleEntryUseReceptionHour=true,false
CollectionDate=true,false
CollectionTime=true,false
SAMPLE_ENTRY_USE_REFFERING_PATIENT_NUMBER=true,false
SampleEntryRequestingSiteSampleId=false,false
PatientIDRequired_SampleConfirmation=false,false
