# Mauritius Form Fields Configuration
# Overrides for MAURITIUS domain
# Format: FieldName=inUse,required,labelKey,label

StNumber=false,false
AKA=false,false
MothersName=false,false
PatientType=false,false
InsuranceNumber=false,false
CollectionDate=true,false
OrgLocalAbrev=false,false
InlineOrganizationTypes=true,false
Occupation=false,false
ADDRESS_DEPARTMENT=false,false
MotherInitial=false,false
ResultsReferral=true,false
ValueHozSpaceOnResults=true,false
InitialSampleCondition=true,false
OrganizationMultiUnit=false,false
OrganizationOrgId=false,false
RequesterSiteList=true,false
SITE_DEPARTMENT=true,false
ADDRESS_CITY=false,false
PatientRequired=true,false
SampleCondition=true,false
NON_CONFORMITY_SITE_LIST=true,false
NON_CONFORMITY_SITE_LIST_USER_ADDABLE=false,false
QaEventsBySection=true,false
PatientNameRequired=false,false
SubjectNumber=true,false
NationalID=true,false
SampleEntryUseReceptionHour=true,false
SampleEntryUseRequestDate=true,false
SampleEntryNextVisitDate=true,false
SampleEntryRequestingSiteSampleId=false,false
SampleEntryReferralSiteNameRequired=true,false
SampleEntryReferralSiteNameCapitialized=true,false
SampleEntryProviderFax=true,false
SampleEntryProviderEmail=true,false
SampleEntryHealthFacilityAddress=false,false
SampleEntrySampleCollector=true,false
PatientPhone=true,false
PatientHealthRegion=true,false,person.health.district
PatientHealthDistrict=false,false
PatientMarriageStatus=true,false
PatientEducation=true,false
SampleEntryPatientClinical=false,false
SampleEntryRequesterPersonRequired=true,false
QATimeWithDate=true,false
SampleEntryReferralSiteCode=false,false
QA_DOCUMENT_NUMBER=false,false
CollectionTime=true,false
TEST_LOCATION_CODE=false,false
ProviderInfo=true,false
SearchSampleStatus=true,false
OrganizationAddressInfo=false,false
DepersonalizedResults=false,false
Project=true,false
NON_CONFORMITY_PROVIDER_ADDRESS=false,false
QA_FULL_PROVIDER_INFO=true,false
QASubjectNumber=false,false
ADDRESS_COMMUNE=true,false,person.streetAddress.street
ADDRESS_VILLAGE=true,false,person.townvillage
SEARCH_PATIENT_WITH_LAB_NO=true,false
SampleNature=true,false
PatientEmail=true,false
