import React, { useState, useContext, useEffect } from "react";
import {
  Modal,
  Button,
  FileUploader,
  Grid,
  Column,
  ProgressBar,
  InlineNotification,
  Select,
  SelectItem,
  Loading,
  Accordion,
  AccordionItem,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListBody,
  StructuredListRow,
  StructuredListCell,
  FileUploaderDropContainer,
  FileUploaderItem,
  Tag,
} from "@carbon/react";
import { Checkmark } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import { NotificationContext } from "../../layout/Layout";
import config from "../../../config.json";
import "./BioanalyticalManifestImportModal.css";

// Bioanalytical-specific expected data points configuration
const EXPECTED_DATA_POINTS = {
  required: [
    {
      label: "Sample ID",
      key: "uniqueSampleId",
      description:
        "Unique identifier for the sample (can retain original or assign new)",
      example: "BIO-2024-001-A, PK-STUDY-001",
    },
    {
      label: "Sample Type",
      key: "sampleType",
      description:
        "Type of bioanalytical sample (API, tablet, biological matrix)",
      example: "API, Tablet, Plasma, Serum, Urine",
    },
    {
      label: "Source Origin",
      key: "sourceOrigin",
      description: "Laboratory or external client providing the sample",
      example: "Medical Laboratory, External Client, CRO Partner",
    },
    {
      label: "Requested Tests",
      key: "requestedTests",
      description: "Analytical tests to be performed on the sample",
      example: "Assay, Dissolution, LC-MS/MS, HPLC, Bioequivalence",
    },
    {
      label: "Date/Time of Receipt",
      key: "dateTimeOfReceipt",
      description:
        "Date and time when sample was received (YYYY-MM-DD HH:MM or 'now')",
      example: "2024-01-15 14:30, now",
    },
    {
      label: "Receiving Personnel",
      key: "receivingPersonnel",
      description: "Name of person who received the sample",
      example: "Dr. Sarah Johnson, Lab Tech Mike",
    },
  ],
  sampleType: [
    {
      label: "Sample Type (Validated)",
      key: "sampleType",
      description:
        "Sample type validated against Bioanalytical & Bioequivalence Laboratory types",
      example: "API, Tablet, Capsule, Plasma, Serum, Urine",
      validValues: [
        "API",
        "Tablet",
        "Capsule",
        "Suspension",
        "Plasma",
        "Serum",
        "Urine",
        "Whole Blood",
        "Reference Standard",
        "Excipient",
        "Stability Sample",
      ],
    },
  ],
  optional: [
    {
      label: "Project/Study Association",
      key: "projectStudyAssociation",
      description:
        "Study or project identifier for bioequivalence or pharmaceutical testing",
      example: "BE-2024-001, STAB-API-001, PK-STUDY-002",
    },
    {
      label: "Storage Condition Prior",
      key: "storageConditionPrior",
      description: "Storage condition before testing",
      example:
        "Room Temperature, Refrigerated (2-8°C), Frozen (-20°C), Ultra-frozen (-80°C)",
    },
    {
      label: "Sample Volume",
      key: "sampleVolume",
      description: "Volume or quantity of the sample with units",
      example: "5 mL, 100 mg, 2 tablets",
    },
    {
      label: "Transport Temperature",
      key: "transportTemperature",
      description: "Temperature during transport in Celsius",
      example: "4°C, -20°C, Ambient",
    },
    {
      label: "Verification Status",
      key: "manifestVerificationStatus",
      description: "Status of manifest verification",
      example: "Verified, Pending, Discrepancy",
    },
    {
      label: "Subject/Patient ID",
      key: "subjectId",
      description: "Subject or patient identifier for bioequivalence studies",
      example: "SUBJ-001, P-101",
    },
    {
      label: "Timepoint",
      key: "timepoint",
      description: "Sampling timepoint for pharmacokinetic studies",
      example: "Pre-dose, 1h, 2h, 4h, 8h, 24h",
    },
    {
      label: "Notes",
      key: "notes",
      description: "Additional notes or observations",
      example: "Sample received in good condition, requires HPLC analysis",
    },
  ],
  autoGenerated: [
    {
      label: "Accession Number",
      key: "accessionNumber",
      description: "System-generated laboratory accession number",
      example: "AUTO-GENERATED",
    },
    {
      label: "Barcode/QR Code",
      key: "barcodeQrCode",
      description: "System-generated scannable identifier",
      example: "AUTO-GENERATED",
    },
  ],
};

/**
 * Enhanced BioanalyticalManifestImportModal - 4-step wizard for CSV manifest import
 * Follows the Immunology Laboratory pattern with bioanalytical-specific fields
 */
function BioanalyticalManifestImportModal({
  open,
  onClose,
  entryId,
  onSuccess,
}) {
  const intl = useIntl();
  const { setNotificationVisible } = useContext(NotificationContext);

  // File upload state
  const [file, setFile] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [validSampleTypes, setValidSampleTypes] = useState([]);

  // Column mapping state - matches bioanalytical data points
  const [columnMapping, setColumnMapping] = useState({
    // Required fields
    uniqueSampleIdColumn: "",
    sampleTypeColumn: "",
    sourceOriginColumn: "",
    requestedTestsColumn: "",
    dateTimeOfReceiptColumn: "",
    receivingPersonnelColumn: "",

    // Optional fields
    projectStudyAssociationColumn: "",
    storageConditionPriorColumn: "",
    sampleVolumeColumn: "",
    transportTemperatureColumn: "",
    manifestVerificationStatusColumn: "",
    subjectIdColumn: "",
    timepointColumn: "",
    notesColumn: "",
  });

  // 4-step wizard state
  const [step, setStep] = useState(1); // 1: upload, 2: mapping, 3: preview, 4: success

  // Preview and import state
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [previewSummary, setPreviewSummary] = useState(null);

  const [isImporting, setIsImporting] = useState(false);
  const [importResults, setImportResults] = useState(null);

  // Load valid bioanalytical sample types on modal open
  useEffect(() => {
    if (open) {
      loadValidSampleTypes();
    }
  }, [open]);

  const loadValidSampleTypes = async () => {
    try {
      const response = await fetch(
        `${config.serverBaseUrl}/rest/notebook/bioanalytical/sample-types`,
        {
          method: "GET",
          credentials: "include",
          headers: {
            "X-CSRF-Token": localStorage.getItem("CSRF"),
          },
        },
      );

      if (response.ok) {
        const data = await response.json();
        setValidSampleTypes(data.sampleTypes || []);
      } else {
        console.warn("Failed to load bioanalytical sample types");
        setValidSampleTypes([]); // Fallback to empty array
      }
    } catch (error) {
      console.warn("Error loading bioanalytical sample types:", error);
      setValidSampleTypes([]); // Fallback to empty array
    }
  };

  // Auto-mapping logic for CSV headers to field names
  const autoMapColumns = (headers) => {
    const normalizeHeader = (header) =>
      header.toLowerCase().replace(/[^a-z0-9]/g, "");

    const columnKeyToField = {
      // Required fields
      uniquesampleid: "uniqueSampleIdColumn",
      sampleid: "uniqueSampleIdColumn",
      id: "uniqueSampleIdColumn",
      sampletype: "sampleTypeColumn",
      type: "sampleTypeColumn",
      sourceorigin: "sourceOriginColumn",
      source: "sourceOriginColumn",
      origin: "sourceOriginColumn",
      laboratory: "sourceOriginColumn",
      client: "sourceOriginColumn",
      requestedtests: "requestedTestsColumn",
      tests: "requestedTestsColumn",
      test: "requestedTestsColumn",
      analysis: "requestedTestsColumn",
      datetimeofreceipt: "dateTimeOfReceiptColumn",
      receiptdatetime: "dateTimeOfReceiptColumn",
      receiptdate: "dateTimeOfReceiptColumn",
      receptiondatetime: "dateTimeOfReceiptColumn",
      receiveddate: "dateTimeOfReceiptColumn",
      receivingpersonnel: "receivingPersonnelColumn",
      personnel: "receivingPersonnelColumn",
      receivedby: "receivingPersonnelColumn",
      receiver: "receivingPersonnelColumn",

      // Optional fields
      projectstudyassociation: "projectStudyAssociationColumn",
      project: "projectStudyAssociationColumn",
      study: "projectStudyAssociationColumn",
      projectname: "projectStudyAssociationColumn",
      studyid: "projectStudyAssociationColumn",
      storagecontitionprior: "storageConditionPriorColumn",
      storage: "storageConditionPriorColumn",
      storagecondition: "storageConditionPriorColumn",
      condition: "storageConditionPriorColumn",
      samplevolume: "sampleVolumeColumn",
      volume: "sampleVolumeColumn",
      quantity: "sampleVolumeColumn",
      amount: "sampleVolumeColumn",
      transporttemperature: "transportTemperatureColumn",
      transport: "transportTemperatureColumn",
      temperature: "transportTemperatureColumn",
      temp: "transportTemperatureColumn",
      manifestverificationstatus: "manifestVerificationStatusColumn",
      verification: "manifestVerificationStatusColumn",
      status: "manifestVerificationStatusColumn",
      verificationstatus: "manifestVerificationStatusColumn",
      subjectid: "subjectIdColumn",
      subject: "subjectIdColumn",
      patientid: "subjectIdColumn",
      patient: "subjectIdColumn",
      timepoint: "timepointColumn",
      time: "timepointColumn",
      sampling: "timepointColumn",
      notes: "notesColumn",
      note: "notesColumn",
      comments: "notesColumn",
      comment: "notesColumn",
      remarks: "notesColumn",
      observation: "notesColumn",
    };

    const newMapping = { ...columnMapping };

    headers.forEach((header) => {
      const normalizedHeader = normalizeHeader(header);
      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  };

  // Check if all required fields are mapped
  const areRequiredFieldsMapped = () => {
    const requiredFields = [
      "uniqueSampleIdColumn",
      "sampleTypeColumn",
      "sourceOriginColumn",
      "requestedTestsColumn",
      "dateTimeOfReceiptColumn",
      "receivingPersonnelColumn",
    ];
    return requiredFields.every((field) => columnMapping[field] !== "");
  };

  const handleFileChange = (files) => {
    if (files && files.length > 0) {
      const selectedFile = files[0];

      // Validate file type
      if (!selectedFile.name.toLowerCase().endsWith(".csv")) {
        setNotificationVisible({
          type: "error",
          message: "Please select a CSV file.",
        });
        return;
      }

      setFile(selectedFile);

      // Parse CSV headers
      const reader = new FileReader();
      reader.onload = (e) => {
        const csv = e.target.result;
        const lines = csv.split("\n");
        if (lines.length > 0) {
          const headers = lines[0]
            .split(",")
            .map((h) => h.trim().replace(/"/g, ""));
          setCsvHeaders(headers);

          // Auto-map columns
          const autoMapped = autoMapColumns(headers);
          setColumnMapping(autoMapped);

          // Advance to mapping step
          setStep(2);
        }
      };
      reader.readAsText(selectedFile);
    }
  };

  const handleColumnMappingChange = (field, value) => {
    setColumnMapping((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handlePreview = async () => {
    if (!file || !entryId) {
      return;
    }

    setIsLoadingPreview(true);
    setPreviewErrors([]);

    try {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("mapping", JSON.stringify(columnMapping));

      const response = await fetch(
        `${config.serverBaseUrl}/rest/notebook/bioanalytical/entry/${entryId}/samples/preview-manifest`,
        {
          method: "POST",
          credentials: "include",
          headers: {
            "X-CSRF-Token": localStorage.getItem("CSRF"),
          },
          body: formData,
        },
      );

      const data = await response.json();

      if (!response.ok) {
        setPreviewErrors(data.errors || []);
        return;
      }

      setPreviewSummary(data);
      setStep(3);
    } catch (error) {
      console.error("Preview error:", error);
      setNotificationVisible({
        type: "error",
        message: `Preview failed: ${error.message}`,
      });
    } finally {
      setIsLoadingPreview(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) {
      return;
    }

    setIsImporting(true);

    try {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("mapping", JSON.stringify(columnMapping));

      const response = await fetch(
        `${config.serverBaseUrl}/rest/notebook/bioanalytical/entry/${entryId}/samples/import-manifest`,
        {
          method: "POST",
          credentials: "include",
          headers: {
            "X-CSRF-Token": localStorage.getItem("CSRF"),
          },
          body: formData,
        },
      );

      const data = await response.json();

      if (!response.ok) {
        setPreviewErrors(data.errors || []);
        setStep(3); // Go back to preview to show errors
        return;
      }

      setImportResults(data);
      setStep(4);

      // Notify parent component of success
      if (onSuccess) {
        setTimeout(() => {
          onSuccess(data);
        }, 1000);
      }
    } catch (error) {
      console.error("Import error:", error);
      setNotificationVisible({
        type: "error",
        message: `Import failed: ${error.message}`,
      });
    } finally {
      setIsImporting(false);
    }
  };

  const handleBack = () => {
    if (step > 1) {
      setStep(step - 1);
    }
  };

  const handleReset = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      uniqueSampleIdColumn: "",
      sampleTypeColumn: "",
      sourceOriginColumn: "",
      requestedTestsColumn: "",
      dateTimeOfReceiptColumn: "",
      receivingPersonnelColumn: "",
      projectStudyAssociationColumn: "",
      storageConditionPriorColumn: "",
      sampleVolumeColumn: "",
      transportTemperatureColumn: "",
      manifestVerificationStatusColumn: "",
      subjectIdColumn: "",
      timepointColumn: "",
      notesColumn: "",
    });
    setPreviewErrors([]);
    setPreviewSummary(null);
    setImportResults(null);
    setStep(1);
  };

  const handleClose = () => {
    handleReset();
    onClose();
  };

  // Generate modal configuration based on current step
  const getModalConfig = () => {
    switch (step) {
      case 1:
        return {
          modalHeading: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.step1.title",
            defaultMessage: "Step 1: Select CSV File",
          }),
          primaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.next",
            defaultMessage: "Next",
          }),
          primaryButtonDisabled: !file,
          onRequestSubmit: () => setStep(2),
          showSecondaryButton: false,
        };
      case 2:
        return {
          modalHeading: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.step2.title",
            defaultMessage: "Step 2: Configure Column Mapping",
          }),
          primaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.preview",
            defaultMessage: "Preview",
          }),
          primaryButtonDisabled: !areRequiredFieldsMapped() || isLoadingPreview,
          onRequestSubmit: handlePreview,
          showSecondaryButton: true,
          secondaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.back",
            defaultMessage: "Back",
          }),
          onSecondarySubmit: handleBack,
        };
      case 3:
        return {
          modalHeading: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.step3.title",
            defaultMessage: "Step 3: Preview & Validate",
          }),
          primaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.import",
            defaultMessage: "Import",
          }),
          primaryButtonDisabled: previewErrors.length > 0 || isImporting,
          onRequestSubmit: handleImport,
          showSecondaryButton: true,
          secondaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.back",
            defaultMessage: "Back",
          }),
          onSecondarySubmit: handleBack,
        };
      case 4:
        return {
          modalHeading: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.step4.title",
            defaultMessage: "Import Complete",
          }),
          primaryButtonText: intl.formatMessage({
            id: "notebook.bioanalytical.manifest.close",
            defaultMessage: "Close",
          }),
          primaryButtonDisabled: false,
          onRequestSubmit: handleClose,
          showSecondaryButton: false,
        };
      default:
        return {};
    }
  };

  const modalConfig = getModalConfig();

  const renderDataPointsReference = () => (
    <Accordion open={!file}>
      <AccordionItem
        title={
          <div className="accordion-title">
            <FormattedMessage
              id="notebook.bioanalytical.manifest.expectedDataPoints"
              defaultMessage="Expected Data Points"
            />
          </div>
        }
      >
        <div className="datapoints-container">
          {/* Required Fields */}
          <div className="datapoints-section">
            <div className="section-title required-title">
              <FormattedMessage
                id="notebook.bioanalytical.manifest.required"
                defaultMessage="Required Fields"
              />
              <Tag type="red" size="sm">
                {EXPECTED_DATA_POINTS.required.length}
              </Tag>
            </div>
            <StructuredListWrapper>
              <StructuredListHead>
                <StructuredListRow>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.field"
                      defaultMessage="Field"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.columnKey"
                      defaultMessage="Column Key"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.description"
                      defaultMessage="Description"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.example"
                      defaultMessage="Example"
                    />
                  </StructuredListCell>
                </StructuredListRow>
              </StructuredListHead>
              <StructuredListBody>
                {EXPECTED_DATA_POINTS.required.map((field, index) => (
                  <StructuredListRow key={index}>
                    <StructuredListCell>{field.label}</StructuredListCell>
                    <StructuredListCell>
                      <code className="column-key">{field.key}</code>
                    </StructuredListCell>
                    <StructuredListCell>{field.description}</StructuredListCell>
                    <StructuredListCell>
                      <em>{field.example}</em>
                    </StructuredListCell>
                  </StructuredListRow>
                ))}
              </StructuredListBody>
            </StructuredListWrapper>
          </div>

          {/* Sample Type Validation */}
          <div className="datapoints-section">
            <div className="section-title sampletype-title">
              <FormattedMessage
                id="notebook.bioanalytical.manifest.sampleType"
                defaultMessage="Sample Type (Validated)"
              />
              <Tag type="purple" size="sm">
                {EXPECTED_DATA_POINTS.sampleType.length}
              </Tag>
            </div>
            <StructuredListWrapper>
              <StructuredListHead>
                <StructuredListRow>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.field"
                      defaultMessage="Field"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.columnKey"
                      defaultMessage="Column Key"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.description"
                      defaultMessage="Description"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.validValues"
                      defaultMessage="Valid Values"
                    />
                  </StructuredListCell>
                </StructuredListRow>
              </StructuredListHead>
              <StructuredListBody>
                {EXPECTED_DATA_POINTS.sampleType.map((field, index) => (
                  <StructuredListRow key={index}>
                    <StructuredListCell>{field.label}</StructuredListCell>
                    <StructuredListCell>
                      <code className="column-key">{field.key}</code>
                    </StructuredListCell>
                    <StructuredListCell>{field.description}</StructuredListCell>
                    <StructuredListCell>
                      <div className="valid-values-list">
                        {field.validValues.slice(0, 5).map((value, i) => (
                          <Tag key={i} type="outline" size="sm">
                            {value}
                          </Tag>
                        ))}
                        {field.validValues.length > 5 && (
                          <Tag type="outline" size="sm">
                            +{field.validValues.length - 5} more
                          </Tag>
                        )}
                      </div>
                    </StructuredListCell>
                  </StructuredListRow>
                ))}
              </StructuredListBody>
            </StructuredListWrapper>
          </div>

          {/* Optional Fields */}
          <div className="datapoints-section">
            <div className="section-title optional-title">
              <FormattedMessage
                id="notebook.bioanalytical.manifest.optional"
                defaultMessage="Optional Fields"
              />
              <Tag type="blue" size="sm">
                {EXPECTED_DATA_POINTS.optional.length}
              </Tag>
            </div>
            <StructuredListWrapper>
              <StructuredListHead>
                <StructuredListRow>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.field"
                      defaultMessage="Field"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.columnKey"
                      defaultMessage="Column Key"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.description"
                      defaultMessage="Description"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.example"
                      defaultMessage="Example"
                    />
                  </StructuredListCell>
                </StructuredListRow>
              </StructuredListHead>
              <StructuredListBody>
                {EXPECTED_DATA_POINTS.optional.map((field, index) => (
                  <StructuredListRow key={index}>
                    <StructuredListCell>{field.label}</StructuredListCell>
                    <StructuredListCell>
                      <code className="column-key">{field.key}</code>
                    </StructuredListCell>
                    <StructuredListCell>{field.description}</StructuredListCell>
                    <StructuredListCell>
                      <em>{field.example}</em>
                    </StructuredListCell>
                  </StructuredListRow>
                ))}
              </StructuredListBody>
            </StructuredListWrapper>
          </div>

          {/* Auto-Generated Fields */}
          <div className="datapoints-section">
            <div className="section-title auto-title">
              <FormattedMessage
                id="notebook.bioanalytical.manifest.autoGenerated"
                defaultMessage="Auto-Generated Fields"
              />
              <Tag type="green" size="sm">
                {EXPECTED_DATA_POINTS.autoGenerated.length}
              </Tag>
            </div>
            <StructuredListWrapper>
              <StructuredListHead>
                <StructuredListRow>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.field"
                      defaultMessage="Field"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.columnKey"
                      defaultMessage="Column Key"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.description"
                      defaultMessage="Description"
                    />
                  </StructuredListCell>
                  <StructuredListCell head>
                    <FormattedMessage
                      id="notebook.bioanalytical.manifest.note"
                      defaultMessage="Note"
                    />
                  </StructuredListCell>
                </StructuredListRow>
              </StructuredListHead>
              <StructuredListBody>
                {EXPECTED_DATA_POINTS.autoGenerated.map((field, index) => (
                  <StructuredListRow key={index}>
                    <StructuredListCell>{field.label}</StructuredListCell>
                    <StructuredListCell>
                      <code className="column-key">{field.key}</code>
                    </StructuredListCell>
                    <StructuredListCell>{field.description}</StructuredListCell>
                    <StructuredListCell>
                      <FormattedMessage
                        id="notebook.bioanalytical.manifest.notInCsv"
                        defaultMessage="Not required in CSV"
                      />
                    </StructuredListCell>
                  </StructuredListRow>
                ))}
              </StructuredListBody>
            </StructuredListWrapper>
          </div>
        </div>
      </AccordionItem>
    </Accordion>
  );

  const renderMappingField = (label, fieldKey, required = false) => (
    <div className={`mapping-field ${required ? "required" : ""}`}>
      <Select
        id={`mapping-${fieldKey}`}
        labelText={required ? `${label} *` : label}
        value={columnMapping[fieldKey]}
        onChange={(e) => handleColumnMappingChange(fieldKey, e.target.value)}
      >
        <SelectItem value="" text="Select column..." />
        {csvHeaders.map((header) => (
          <SelectItem key={header} value={header} text={header} />
        ))}
      </Select>
      {required && <span className="required-marker">*</span>}
    </div>
  );

  const renderStepContent = () => {
    switch (step) {
      case 1:
        return (
          <div className="upload-step">
            {renderDataPointsReference()}
            <div style={{ marginTop: "2rem" }}>
              <FileUploaderDropContainer
                accept={[".csv"]}
                labelText="Drag and drop CSV file here or click to upload"
                multiple={false}
                name="csvFile"
                onAddFiles={handleFileChange}
              />
              {file && (
                <FileUploaderItem
                  name={file.name}
                  status="edit"
                  iconDescription="Remove file"
                  onDelete={() => setFile(null)}
                />
              )}
            </div>
          </div>
        );

      case 2:
        return (
          <div className="mapping-step">
            <h4>
              <FormattedMessage
                id="notebook.bioanalytical.manifest.columnMapping"
                defaultMessage="Column Mapping"
              />
            </h4>
            <p style={{ marginBottom: "1.5rem" }}>
              <FormattedMessage
                id="notebook.bioanalytical.manifest.mappingInstructions"
                defaultMessage="Map your CSV columns to the expected bioanalytical fields. Required fields are marked with *"
              />
            </p>

            {/* Required Fields */}
            <div className="mapping-section">
              <h5 className="mapping-section-title required-title">
                <FormattedMessage
                  id="notebook.bioanalytical.manifest.requiredFieldsMapping"
                  defaultMessage="Required Fields"
                />
                <Tag type="red" size="sm">
                  6
                </Tag>
              </h5>
              <div className="mapping-grid">
                {renderMappingField("Sample ID", "uniqueSampleIdColumn", true)}
                {renderMappingField("Sample Type", "sampleTypeColumn", true)}
                {renderMappingField(
                  "Source Origin",
                  "sourceOriginColumn",
                  true,
                )}
                {renderMappingField(
                  "Requested Tests",
                  "requestedTestsColumn",
                  true,
                )}
                {renderMappingField(
                  "Date/Time of Receipt",
                  "dateTimeOfReceiptColumn",
                  true,
                )}
                {renderMappingField(
                  "Receiving Personnel",
                  "receivingPersonnelColumn",
                  true,
                )}
              </div>
            </div>

            {/* Sample Type Validation Info */}
            <div className="mapping-section">
              <h5 className="mapping-section-title sampletype-title">
                <FormattedMessage
                  id="notebook.bioanalytical.manifest.sampleTypeValidation"
                  defaultMessage="Sample Type Validation"
                />
                <Tag type="purple" size="sm">
                  Validated
                </Tag>
              </h5>
              <p className="mapping-section-info">
                <FormattedMessage
                  id="notebook.bioanalytical.manifest.sampleTypeInfo"
                  defaultMessage="Sample types will be validated against Bioanalytical & Bioequivalence Laboratory types. Invalid types will be rejected during preview."
                />
              </p>
            </div>

            {/* Optional Fields */}
            <div className="mapping-section">
              <h5 className="mapping-section-title optional-title">
                <FormattedMessage
                  id="notebook.bioanalytical.manifest.optionalFieldsMapping"
                  defaultMessage="Optional Fields"
                />
                <Tag type="blue" size="sm">
                  8
                </Tag>
              </h5>
              <div className="mapping-grid">
                {renderMappingField(
                  "Project/Study Association",
                  "projectStudyAssociationColumn",
                )}
                {renderMappingField(
                  "Storage Condition Prior",
                  "storageConditionPriorColumn",
                )}
                {renderMappingField("Sample Volume", "sampleVolumeColumn")}
                {renderMappingField(
                  "Transport Temperature",
                  "transportTemperatureColumn",
                )}
                {renderMappingField(
                  "Verification Status",
                  "manifestVerificationStatusColumn",
                )}
                {renderMappingField("Subject/Patient ID", "subjectIdColumn")}
                {renderMappingField("Timepoint", "timepointColumn")}
                {renderMappingField("Notes", "notesColumn")}
              </div>
            </div>
          </div>
        );

      case 3:
        return (
          <div className="preview-step">
            {isLoadingPreview ? (
              <Loading
                description={intl.formatMessage({
                  id: "notebook.bioanalytical.manifest.validating",
                  defaultMessage: "Validating manifest data...",
                })}
              />
            ) : (
              <>
                {previewErrors.length > 0 ? (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.bioanalytical.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={intl.formatMessage({
                      id: "notebook.bioanalytical.manifest.errorsFound",
                      defaultMessage:
                        "Please fix the following errors before importing:",
                    })}
                    lowContrast
                  />
                ) : null}

                {previewErrors.length > 0 && (
                  <ul className="error-list">
                    {previewErrors.map((error, index) => (
                      <li key={index}>
                        Row {error.rowNumber}, Column "{error.column}":{" "}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                )}

                {previewSummary && (
                  <div className="preview-summary">
                    <Tag type="gray" size="sm">
                      Total Rows: {previewSummary.totalRows}
                    </Tag>
                    <Tag type="green" size="sm">
                      Samples to Create: {previewSummary.totalSamplesToCreate}
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        );

      case 4:
        return (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h4>
              <FormattedMessage
                id="notebook.bioanalytical.manifest.importSuccess"
                defaultMessage="Import Successful!"
              />
            </h4>
            {importResults && (
              <p>
                <FormattedMessage
                  id="notebook.bioanalytical.manifest.samplesCreated"
                  defaultMessage="{count} bioanalytical samples have been successfully imported and are ready for processing."
                  values={{ count: importResults.totalCreated }}
                />
              </p>
            )}
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={modalConfig.modalHeading}
      primaryButtonText={modalConfig.primaryButtonText}
      primaryButtonDisabled={modalConfig.primaryButtonDisabled}
      onRequestSubmit={modalConfig.onRequestSubmit}
      secondaryButtonText={
        modalConfig.showSecondaryButton
          ? modalConfig.secondaryButtonText
          : undefined
      }
      onSecondarySubmit={
        modalConfig.showSecondaryButton
          ? modalConfig.onSecondarySubmit
          : undefined
      }
      size="lg"
      className="manifest-import-modal"
    >
      {renderStepContent()}
    </Modal>
  );
}

export default BioanalyticalManifestImportModal;
