# Haiti Clinical Form Fields Configuration
# Overrides for HAITI domain
# Format: FieldName=inUse,required,labelKey,label

InlineOrganizationTypes=true,false
DepersonalizedResults=true,false
OrgLocalAbrev=false,false
OrganizationMultiUnit=false,false
OrganizationOrgId=false,false
ADDRESS_CITY=false,false
ADDRESS_DEPARTMENT=true,false
PatientRequired=true,false
SampleCondition=true,false
NON_CONFORMITY_SITE_LIST=true,false
ValueHozSpaceOnResults=true,false
SampleEntryUseReceptionHour=true,false
CollectionDate=true,false
CollectionTime=true,false
SAMPLE_ENTRY_USE_REFFERING_PATIENT_NUMBER=true,false
SampleEntryRequestingSiteSampleId=false,false
