# Kenya Form Fields Configuration
# This file overrides defaults for KENYA domain

StNumber=false,false
AKA=false,false
MothersName=false,false
PatientType=false,false
InsuranceNumber=false,false
CollectionDate=true,false
OrgLocalAbrev=false,false
InlineOrganizationTypes=true,false
Occupation=false,false
ADDRESS_DEPARTMENT=false,false
MotherInitial=false,false
ResultsReferral=true,false
ValueHozSpaceOnResults=true,false
InitialSampleCondition=true,false
OrganizationMultiUnit=false,false
OrganizationOrgId=false,false
RequesterSiteList=true,false
ADDRESS_CITY=false,false
PatientRequired=true,false
SampleCondition=false,false
NON_CONFORMITY_SITE_LIST=true,false
NON_CONFORMITY_SITE_LIST_USER_ADDABLE=true,false
PatientNameRequired=false,false
SubjectNumber=true,false
NationalID=true,false
SampleEntryUseReceptionHour=true,false
SampleEntryUseRequestDate=true,false
SampleEntryNextVisitDate=true,false
SampleEntryRequestingSiteSampleId=false,false
SampleEntryReferralSiteNameRequired=true,false
SampleEntryReferralSiteNameCapitialized=true,false
SampleEntryProviderFax=true,false
SampleEntryProviderEmail=true,false
SampleEntryHealthFacilityAddress=false,false
SampleEntrySampleCollector=true,false
PatientPhone=true,false
PatientHealthRegion=true,false,person.health.region
PatientHealthDistrict=true,false,person.health.district
PatientMarriageStatus=true,false
PatientEducation=true,false
SampleEntryPatientClinical=false,false
SampleEntryRequesterPersonRequired=true,false
QASubjectNumber=true,false
QATimeWithDate=true,false

