# CI LNSP Form Fields Configuration
# Overrides for LNSP_CI domain
# Format: FieldName=inUse,required,labelKey,label

StNumber=false,false
AKA=false,false
MothersName=false,false
PatientType=false,false
InsuranceNumber=false,false
CollectionDate=true,false
OrgLocalAbrev=false,false
InlineOrganizationTypes=true,false
Occupation=false,false
ADDRESS_DEPARTMENT=false,false
MotherInitial=false,false
ResultsReferral=true,false
ValueHozSpaceOnResults=true,false
InitialSampleCondition=true,false
OrganizationMultiUnit=false,false
OrganizationOrgId=false,false
RequesterSiteList=true,false
ADDRESS_CITY=false,false
PatientRequired=true,false
SampleCondition=false,false
NON_CONFORMITY_SITE_LIST=true,false
NON_CONFORMITY_SITE_LIST_USER_ADDABLE=true,false
PatientNameRequired=false,false
SubjectNumber=true,false
NationalID=true,false
SampleEntryUseReceptionHour=true,false
SampleEntryUseRequestDate=true,false
SampleEntryNextVisitDate=true,false
SampleEntryRequestingSiteSampleId=false,false
SampleEntryReferralSiteNameRequired=true,false
SampleEntryReferralSiteNameCapitialized=true,false
SampleEntryReferralSiteCode=true,false
SampleEntryProviderFax=true,false
SampleEntryProviderEmail=true,false
SampleEntryHealthFacilityAddress=false,false
SampleEntrySampleCollector=true,false
PatientPhone=true,false
PatientHealthRegion=true,false
PatientHealthDistrict=true,false
PatientMarriageStatus=true,false
PatientEducation=true,false
SampleEntryPatientClinical=false,false
SampleEntryRequesterPersonRequired=true,false
QA_DOCUMENT_NUMBER=true,false
QATimeWithDate=true,false
SEARCH_PATIENT_WITH_LAB_NO=true,false
CollectionTime=true,false
TEST_LOCATION_CODE=true,false
DepersonalizedResults=false,false
