package org.openelisglobal.qaevent.qiconfig.breach;

import java.sql.Date;
import org.openelisglobal.qaevent.qiconfig.valueholder.QiIndicator;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QiBreachNceServiceImpl implements QiBreachNceService {

    public static final String TRIGGER_SOURCE_QI_BREACH = "QI_BREACH";

    private static final String NCE_SEVERITY = "CRITICAL";

    @Autowired
    private NCEventService ncEventService;

    // REQUIRES_NEW so a number collision or failure here is isolated from the
    // evaluator loop and a retry starts clean (mirrors QcViolationNceServiceImpl).
    // The (trigger_source_type, trigger_source_id) unique constraint (migration
    // 051) is the backstop; the pre-check keeps the happy path collision-free.
    @Override
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public NcEvent createBreachNce(QiIndicator indicator, String periodKey, String summary) {
        NcEvent nce = new NcEvent();
        nce.setSysUserId(NCEventService.SYSTEM_USER_ID);
        nce.setSeverity(NCE_SEVERITY);
        nce.setTriggerSourceType(TRIGGER_SOURCE_QI_BREACH);
        nce.setTriggerSourceId(indicator.name() + ":" + periodKey);
        nce.setTitle("QI threshold breach — " + indicator.name() + " (" + periodKey + ")");
        nce.setDescription("Auto-created from QI monitoring. " + summary + ".");
        nce.setImmediateAction("Review the indicator trend and investigate the cause");
        nce.setNameOfReporter("System (QI monitoring)");
        nce.setDateOfEvent(new Date(System.currentTimeMillis()));

        return ncEventService.createAutoGenerated(nce, "Auto-created from QI threshold breach: " + summary, null);
    }
}
