#!/bin/bash
#
# extract-user-data.sh
#
# Extracts users, departments, lab units, and measurement units from an OpenELIS database.
# The output SQL file can be used to populate another database.
#
# Usage:
#   ./scripts/extract-user-data.sh [OPTIONS]
#
# Options:
#   --container     Docker container name (default: openelisglobal-database)
#   -d, --database  Database name (default: clinlims)
#   -U, --user      Database user (default: clinlims)
#   -o, --output    Output SQL file (default: user-data-export.sql)
#   --no-passwords  Export users without password hashes (more secure)
#   --help          Show this help message
#
# Output includes:
#   - System users (login_user, system_user)
#   - User roles and permissions (system_user_role, system_user_section, system_user_module)
#   - Departments/Test sections (test_section)
#   - Organizations (organization, organization_type, organization_organization_type)
#   - Lab unit role mappings (user_lab_unit_roles, lab_unit_role_map, lab_unit_roles, lab_roles)
#   - Measurement units (unit_of_measure)
#   - System roles and modules (system_role, system_module, system_role_module)
#

set -e

# Default values
CONTAINER="${CONTAINER:-openelisglobal-database}"
DB_NAME="${DB_NAME:-clinlims}"
DB_USER="${DB_USER:-clinlims}"
OUTPUT_FILE="user-data-export.sql"
EXPORT_PASSWORDS=true

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --container)
            CONTAINER="$2"
            shift 2
            ;;
        -d|--database)
            DB_NAME="$2"
            shift 2
            ;;
        -U|--user)
            DB_USER="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --no-passwords)
            EXPORT_PASSWORDS=false
            shift
            ;;
        --help)
            head -28 "$0" | tail -25
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Check if docker is available
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: docker command not found. Please install Docker.${NC}"
    exit 1
fi

# Check if container is running
if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
    echo -e "${RED}Error: Container '${CONTAINER}' is not running.${NC}"
    echo "Running containers:"
    docker ps --format '  {{.Names}}'
    exit 1
fi

echo -e "${GREEN}=== User Data Extraction Script ===${NC}"
echo "Container: ${CONTAINER}"
echo "Database: ${DB_NAME}"
echo "User: ${DB_USER}"
echo "Output: ${OUTPUT_FILE}"
echo "Export passwords: ${EXPORT_PASSWORDS}"
echo ""

# Function to execute SQL via Docker
execute_sql() {
    docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A "$@"
}

# Initialize output file
cat > "$OUTPUT_FILE" << 'HEADER'
--
-- OpenELIS Global User Data Export
-- Generated by extract-user-data.sh
--
-- This file contains:
--   - System roles and modules
--   - Login users and system users
--   - User role assignments and permissions
--   - Departments (test sections)
--   - Organizations and organization types
--   - Lab unit role mappings
--   - Units of measure
--
-- To import: ./scripts/populate-user-data.sh -i <this-file>
--

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

BEGIN;

HEADER

echo -e "${YELLOW}Extracting system roles...${NC}"
echo "-- System Roles" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_role (id, name, description, is_grouping_role, grouping_parent, display_key, active, editable) VALUES ('
    || id || ', '
    || quote_literal(name) || ', '
    || COALESCE(quote_literal(description), 'NULL') || ', '
    || COALESCE(is_grouping_role::text, 'false') || ', '
    || COALESCE(grouping_parent::text, 'NULL') || ', '
    || COALESCE(quote_literal(display_key), 'NULL') || ', '
    || COALESCE(active::text, 'true') || ', '
    || COALESCE(editable::text, 'false')
    || ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_grouping_role = EXCLUDED.is_grouping_role, grouping_parent = EXCLUDED.grouping_parent, display_key = EXCLUDED.display_key, active = EXCLUDED.active, editable = EXCLUDED.editable;'
FROM clinlims.system_role
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting system modules...${NC}"
echo "-- System Modules" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_module (id, name, description, has_select_flag, has_add_flag, has_update_flag, has_delete_flag) VALUES ('
    || id || ', '
    || quote_literal(name) || ', '
    || COALESCE(quote_literal(description), 'NULL') || ', '
    || quote_literal(COALESCE(has_select_flag, 'Y')) || ', '
    || quote_literal(COALESCE(has_add_flag, 'Y')) || ', '
    || quote_literal(COALESCE(has_update_flag, 'Y')) || ', '
    || quote_literal(COALESCE(has_delete_flag, 'Y'))
    || ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;'
FROM clinlims.system_module
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting system role-module mappings...${NC}"
echo "-- System Role Module Mappings" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_role_module (id, has_select, has_add, has_update, has_delete, system_role_id, system_module_id) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(has_select), '''Y''') || ', '
    || COALESCE(quote_literal(has_add), '''Y''') || ', '
    || COALESCE(quote_literal(has_update), '''Y''') || ', '
    || COALESCE(quote_literal(has_delete), '''Y''') || ', '
    || system_role_id || ', '
    || system_module_id
    || ') ON CONFLICT (id) DO NOTHING;'
FROM clinlims.system_role_module
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting organization types...${NC}"
echo "-- Organization Types" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.organization_type (id, short_name, description, name_display_key, lastupdated) VALUES ('
    || id || ', '
    || quote_literal(short_name) || ', '
    || COALESCE(quote_literal(description), 'NULL') || ', '
    || COALESCE(quote_literal(name_display_key), 'NULL') || ', '
    || 'NOW()'
    || ') ON CONFLICT (id) DO UPDATE SET short_name = EXCLUDED.short_name, description = EXCLUDED.description, name_display_key = EXCLUDED.name_display_key;'
FROM clinlims.organization_type
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting organizations...${NC}"
echo "-- Organizations" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.organization (id, name, city, zip_code, mls_sentinel_lab_flag, org_mlt_org_mlt_id, org_id, short_name, multiple_unit, street_address, state, internet_address, clia_num, pws_id, lastupdated, mls_lab_flag, is_active, local_abbrev, code, datim_org_code, datim_org_name) VALUES ('
    || id || ', '
    || quote_literal(name) || ', '
    || COALESCE(quote_literal(city), 'NULL') || ', '
    || COALESCE(quote_literal(zip_code), 'NULL') || ', '
    || COALESCE(quote_literal(mls_sentinel_lab_flag), '''N''') || ', '
    || COALESCE(org_mlt_org_mlt_id::text, 'NULL') || ', '
    || COALESCE(org_id::text, 'NULL') || ', '
    || COALESCE(quote_literal(short_name), 'NULL') || ', '
    || COALESCE(quote_literal(multiple_unit), 'NULL') || ', '
    || COALESCE(quote_literal(street_address), 'NULL') || ', '
    || COALESCE(quote_literal(state), 'NULL') || ', '
    || COALESCE(quote_literal(internet_address), 'NULL') || ', '
    || COALESCE(quote_literal(clia_num), 'NULL') || ', '
    || COALESCE(quote_literal(pws_id), 'NULL') || ', '
    || 'NOW(), '
    || COALESCE(quote_literal(mls_lab_flag), 'NULL') || ', '
    || COALESCE(quote_literal(is_active), '''Y''') || ', '
    || COALESCE(quote_literal(local_abbrev), 'NULL') || ', '
    || COALESCE(quote_literal(code), 'NULL') || ', '
    || COALESCE(quote_literal(datim_org_code), 'NULL') || ', '
    || COALESCE(quote_literal(datim_org_name), 'NULL')
    || ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, is_active = EXCLUDED.is_active, code = EXCLUDED.code;'
FROM clinlims.organization
ORDER BY COALESCE(org_id, 0), id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting organization-type mappings...${NC}"
echo "-- Organization-Type Mappings" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.organization_organization_type (org_id, org_type_id) VALUES ('
    || org_id || ', '
    || org_type_id
    || ') ON CONFLICT DO NOTHING;'
FROM clinlims.organization_organization_type
ORDER BY org_id, org_type_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting localization entries for test sections...${NC}"
echo "-- Localization entries for test sections" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.localization (id, description, english, french, lastupdated) VALUES ('
    || l.id || ', '
    || COALESCE(quote_literal(l.description), '''test section name''') || ', '
    || COALESCE(quote_literal(l.english), 'NULL') || ', '
    || COALESCE(quote_literal(l.french), 'NULL') || ', '
    || 'NOW()'
    || ') ON CONFLICT (id) DO UPDATE SET english = EXCLUDED.english, french = EXCLUDED.french;'
FROM clinlims.localization l
INNER JOIN clinlims.test_section ts ON ts.name_localization_id = l.id
ORDER BY l.id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting test sections (departments)...${NC}"
echo "-- Test Sections (Departments/Lab Units)" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.test_section (id, name, description, org_id, is_external, lastupdated, parent_test_section, sort_order, is_active, name_localization_id, display_key) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(name), 'NULL') || ', '
    || quote_literal(description) || ', '
    || COALESCE(org_id::text, 'NULL') || ', '
    || COALESCE(quote_literal(is_external), 'NULL') || ', '
    || 'NOW(), '
    || COALESCE(parent_test_section::text, 'NULL') || ', '
    || COALESCE(sort_order::text, '2147483647') || ', '
    || COALESCE(quote_literal(is_active), '''Y''') || ', '
    || COALESCE(name_localization_id::text, 'NULL') || ', '
    || COALESCE(quote_literal(display_key), 'NULL')
    || ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, display_key = EXCLUDED.display_key;'
FROM clinlims.test_section
ORDER BY COALESCE(parent_test_section, 0), id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting units of measure...${NC}"
echo "-- Units of Measure" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.unit_of_measure (id, name, description, lastupdated) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(name), 'NULL') || ', '
    || COALESCE(quote_literal(description), 'NULL') || ', '
    || 'NOW()'
    || ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;'
FROM clinlims.unit_of_measure
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

# Export login users with or without passwords
echo -e "${YELLOW}Extracting login users...${NC}"
if [ "$EXPORT_PASSWORDS" = true ]; then
    echo "-- Login Users (with password hashes)" >> "$OUTPUT_FILE"
    docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.login_user (id, login_name, password, password_expired_dt, account_locked, account_disabled, is_admin, user_time_out) VALUES ('
    || id || ', '
    || quote_literal(login_name) || ', '
    || quote_literal(password) || ', '
    || quote_literal(password_expired_dt::text) || ', '
    || quote_literal(account_locked) || ', '
    || quote_literal(account_disabled) || ', '
    || quote_literal(is_admin) || ', '
    || quote_literal(user_time_out)
    || ') ON CONFLICT (id) DO UPDATE SET login_name = EXCLUDED.login_name, password = EXCLUDED.password, account_locked = EXCLUDED.account_locked, account_disabled = EXCLUDED.account_disabled, is_admin = EXCLUDED.is_admin;'
FROM clinlims.login_user
ORDER BY id;
EOF
else
    # Export without actual password hashes - use a default placeholder
    echo "-- Login Users (passwords redacted - users will need to reset)" >> "$OUTPUT_FILE"
    docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.login_user (id, login_name, password, password_expired_dt, account_locked, account_disabled, is_admin, user_time_out) VALUES ('
    || id || ', '
    || quote_literal(login_name) || ', '
    || '''$2a$10$PLACEHOLDER_HASH_NEEDS_RESET'', '
    || quote_literal(CURRENT_DATE::text) || ', '
    || quote_literal(account_locked) || ', '
    || quote_literal(account_disabled) || ', '
    || quote_literal(is_admin) || ', '
    || quote_literal(user_time_out)
    || ') ON CONFLICT (id) DO UPDATE SET login_name = EXCLUDED.login_name, account_locked = EXCLUDED.account_locked, account_disabled = EXCLUDED.account_disabled, is_admin = EXCLUDED.is_admin;'
FROM clinlims.login_user
ORDER BY id;
EOF
fi
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting system users...${NC}"
echo "-- System Users" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_user (id, external_id, login_name, last_name, first_name, initials, is_active, is_employee, lastupdated) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(external_id), 'NULL') || ', '
    || quote_literal(login_name) || ', '
    || quote_literal(last_name) || ', '
    || quote_literal(first_name) || ', '
    || COALESCE(quote_literal(initials), 'NULL') || ', '
    || quote_literal(is_active) || ', '
    || quote_literal(is_employee) || ', '
    || 'NOW()'
    || ') ON CONFLICT (id) DO UPDATE SET login_name = EXCLUDED.login_name, last_name = EXCLUDED.last_name, first_name = EXCLUDED.first_name, is_active = EXCLUDED.is_active;'
FROM clinlims.system_user
ORDER BY id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting user role assignments...${NC}"
echo "-- User Role Assignments" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_user_role (system_user_id, role_id) VALUES ('
    || system_user_id || ', '
    || role_id
    || ') ON CONFLICT DO NOTHING;'
FROM clinlims.system_user_role
ORDER BY system_user_id, role_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting user section permissions...${NC}"
echo "-- User Section (Department) Permissions" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_user_section (id, has_view, has_assign, has_complete, has_release, has_cancel, system_user_id, test_section_id) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(has_view), '''Y''') || ', '
    || COALESCE(quote_literal(has_assign), '''Y''') || ', '
    || COALESCE(quote_literal(has_complete), '''Y''') || ', '
    || COALESCE(quote_literal(has_release), '''Y''') || ', '
    || COALESCE(quote_literal(has_cancel), '''Y''') || ', '
    || system_user_id || ', '
    || test_section_id
    || ') ON CONFLICT (id) DO NOTHING;'
FROM clinlims.system_user_section
ORDER BY system_user_id, test_section_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting user module permissions...${NC}"
echo "-- User Module Permissions" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.system_user_module (id, has_select, has_add, has_update, has_delete, system_user_id, system_module_id) VALUES ('
    || id || ', '
    || COALESCE(quote_literal(has_select), '''Y''') || ', '
    || COALESCE(quote_literal(has_add), '''Y''') || ', '
    || COALESCE(quote_literal(has_update), '''Y''') || ', '
    || COALESCE(quote_literal(has_delete), '''Y''') || ', '
    || system_user_id || ', '
    || system_module_id
    || ') ON CONFLICT (id) DO NOTHING;'
FROM clinlims.system_user_module
ORDER BY system_user_id, system_module_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting user lab unit roles container...${NC}"
echo "-- User Lab Unit Roles Container" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.user_lab_unit_roles (system_user_id, last_updated) VALUES ('
    || system_user_id || ', '
    || 'NOW()'
    || ') ON CONFLICT (system_user_id) DO NOTHING;'
FROM clinlims.user_lab_unit_roles
ORDER BY system_user_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting lab unit role mappings...${NC}"
echo "-- Lab Unit Role Map" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.lab_unit_role_map (lab_unit_role_map_id, lab_unit) VALUES ('
    || lab_unit_role_map_id || ', '
    || quote_literal(lab_unit)
    || ') ON CONFLICT (lab_unit_role_map_id) DO NOTHING;'
FROM clinlims.lab_unit_role_map
ORDER BY lab_unit_role_map_id;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting lab roles...${NC}"
echo "-- Lab Roles (roles within lab units)" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.lab_roles (lab_unit_role_map_id, role) VALUES ('
    || lab_unit_role_map_id || ', '
    || quote_literal(role)
    || ') ON CONFLICT DO NOTHING;'
FROM clinlims.lab_roles
ORDER BY lab_unit_role_map_id, role;
EOF
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}Extracting user-lab unit role assignments...${NC}"
echo "-- User Lab Unit Role Assignments" >> "$OUTPUT_FILE"
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -A << 'EOF' >> "$OUTPUT_FILE"
SELECT 'INSERT INTO clinlims.lab_unit_roles (system_user_id, lab_unit_role_map_id) VALUES ('
    || system_user_id || ', '
    || lab_unit_role_map_id
    || ') ON CONFLICT DO NOTHING;'
FROM clinlims.lab_unit_roles
ORDER BY system_user_id, lab_unit_role_map_id;
EOF
echo "" >> "$OUTPUT_FILE"

# Add sequence updates at the end
echo -e "${YELLOW}Adding sequence updates...${NC}"
cat >> "$OUTPUT_FILE" << 'SEQUENCES'
-- Update sequences to avoid ID conflicts
SELECT setval('clinlims.login_user_seq', (COALESCE((SELECT MAX(id) FROM clinlims.login_user), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_user_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_user), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_role_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_role), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_module_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_module), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_role_module_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_role_module), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_user_module_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_user_module), 0) + 1)::bigint, false);
SELECT setval('clinlims.system_user_section_seq', (COALESCE((SELECT MAX(id) FROM clinlims.system_user_section), 0) + 1)::bigint, false);
SELECT setval('clinlims.organization_seq', (COALESCE((SELECT MAX(id) FROM clinlims.organization), 0) + 1)::bigint, false);
SELECT setval('clinlims.organization_type_seq', (COALESCE((SELECT MAX(id) FROM clinlims.organization_type), 0) + 1)::bigint, false);
SELECT setval('clinlims.test_section_seq', (COALESCE((SELECT MAX(id) FROM clinlims.test_section), 0) + 1)::bigint, false);
SELECT setval('clinlims.unit_of_measure_seq', (COALESCE((SELECT MAX(id) FROM clinlims.unit_of_measure), 0) + 1)::bigint, false);
SELECT setval('clinlims.localization_seq', (COALESCE((SELECT MAX(id) FROM clinlims.localization), 0) + 1)::bigint, false);

COMMIT;

-- Data import complete!
SEQUENCES

echo ""
echo -e "${GREEN}=== Extraction Complete ===${NC}"
echo ""

# Print summary
echo -e "${CYAN}Summary of extracted data:${NC}"
execute_sql << 'EOF'
SELECT 'System Roles' as entity, COUNT(*)::text as count FROM clinlims.system_role
UNION ALL SELECT 'System Modules', COUNT(*)::text FROM clinlims.system_module
UNION ALL SELECT 'Role-Module Mappings', COUNT(*)::text FROM clinlims.system_role_module
UNION ALL SELECT 'Organization Types', COUNT(*)::text FROM clinlims.organization_type
UNION ALL SELECT 'Organizations', COUNT(*)::text FROM clinlims.organization
UNION ALL SELECT 'Test Sections (Depts)', COUNT(*)::text FROM clinlims.test_section
UNION ALL SELECT 'Units of Measure', COUNT(*)::text FROM clinlims.unit_of_measure
UNION ALL SELECT 'Login Users', COUNT(*)::text FROM clinlims.login_user
UNION ALL SELECT 'System Users', COUNT(*)::text FROM clinlims.system_user
UNION ALL SELECT 'User Roles', COUNT(*)::text FROM clinlims.system_user_role
UNION ALL SELECT 'User Section Perms', COUNT(*)::text FROM clinlims.system_user_section
UNION ALL SELECT 'User Module Perms', COUNT(*)::text FROM clinlims.system_user_module
UNION ALL SELECT 'Lab Unit Role Maps', COUNT(*)::text FROM clinlims.lab_unit_role_map
UNION ALL SELECT 'Lab Unit Roles', COUNT(*)::text FROM clinlims.lab_unit_roles;
EOF

echo ""
echo -e "${GREEN}Output saved to: ${OUTPUT_FILE}${NC}"
echo ""
echo "To import this data into another database:"
echo "  ./scripts/populate-user-data.sh -i ${OUTPUT_FILE}"
