# CI RETRO Form Fields Configuration
# Overrides for CDI domain
# Format: FieldName=inUse,required,labelKey,label

StNumber=false,false
AKA=false,false
MothersName=false,false
PatientType=true,false
InsuranceNumber=false,false
CollectionDate=true,false
OrgLocalAbrev=false,false
InlineOrganizationTypes=true,false
ProviderInfo=false,false
NationalID=true,false
SearchSampleStatus=true,false
OrganizationAddressInfo=false,false
DepersonalizedResults=true,false
SEARCH_PATIENT_WITH_LAB_NO=true,false
Project=true,false
QA_FULL_PROVIDER_INFO=false,false
QASubjectNumber=false,false
ADDRESS_COMMUNE=false,false
ADDRESS_VILLAGE=false,false
