import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
} from "@carbon/react";
import { Upload, Checkmark, Warning, Information } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for GBD (Genomics & Bioinformatics Database) Sample Reception Manifest.
 * Aligned with the genomic workflow reception and processing metadata requirements.
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "sampleId",
      label: "Sample ID",
      description: "Unique sample identifier assigned by the source laboratory",
      example: "GBD-2024-001-A",
    },
    {
      key: "sampleType",
      label: "Sample Type",
      description:
        "Type of genomic sample (DNA, RNA, tissue, swabs, isolates, PCR products, libraries)",
      example: "DNA, RNA, tissue",
    },
    {
      key: "source",
      label: "Source/Origin",
      description: "Facility or study site where sample was collected",
      example: "Research Hospital Addis Ababa",
    },
    {
      key: "collectionDate",
      label: "Collection Date",
      description: "Date of sample collection (YYYY-MM-DD)",
      example: "2024-01-15",
    },
    {
      key: "receptionDateTime",
      label: "Reception Date & Time",
      description:
        "Date and time of sample reception at lab (YYYY-MM-DD HH:MM or 'now')",
      example: "2024-01-16 14:00",
    },
  ],
  sampleType: {
    key: "sampleType",
    label: "Sample Type",
    description: "Type of genomic sample (validated against GBD lab types)",
    example:
      "DNA, RNA, tissue, swabs, bacterial/viral isolates, PCR products, libraries",
  },
  optional: [
    {
      key: "projectStudyAssociation",
      label: "Project/Study Association",
      description: "Research project or study identifier",
      example: "PROJ-GENOMICS-2024",
    },
    {
      key: "volumeConcentration",
      label: "Volume/Concentration",
      description: "Volume (mL) or concentration (ng/µL) of sample",
      example: "5 mL, 50 ng/µL",
    },
    {
      key: "a260_280",
      label: "A260/280 Ratio",
      description:
        "Purity metric for nucleic acid (protein contamination indicator)",
      example: "1.8-2.0",
    },
    {
      key: "a260_230",
      label: "A260/230 Ratio",
      description:
        "Purity metric for nucleic acid (salt contamination indicator)",
      example: "2.0-2.2",
    },
    {
      key: "rin",
      label: "RIN (RNA Integrity Number)",
      description: "RNA quality metric (1-10, higher is better)",
      example: "8.5",
    },
    {
      key: "extractionMethodKit",
      label: "Extraction Method/Kit",
      description: "DNA/RNA extraction protocol or commercial kit used",
      example: "Qiagen DNeasy Blood & Tissue Kit",
    },
    {
      key: "pcrProtocol",
      label: "PCR Protocol",
      description: "PCR amplification protocol or kit details",
      example: "KAPA PCR Kit, 35 cycles",
    },
    {
      key: "libraryPrepProtocol",
      label: "Library Preparation Protocol",
      description: "Library preparation method and kit",
      example: "Illumina TruSeq DNA Library Prep",
    },
    {
      key: "sequencingPlatform",
      label: "Sequencing Platform",
      description: "Sequencing platform if applicable",
      example: "Illumina NovaSeq, PacBio Sequel",
    },
    {
      key: "runId",
      label: "Run ID",
      description: "Sequencing run identifier",
      example: "RUN-2024-001",
    },
    {
      key: "operator",
      label: "Operator Name",
      description: "Name of laboratory technician who processed the sample",
      example: "Dr. Abebe Kemal",
    },
    {
      key: "processingDateTime",
      label: "Processing Date & Time",
      description: "Date and time of sample processing (YYYY-MM-DD HH:MM)",
      example: "2024-01-17 10:30",
    },
    {
      key: "notes",
      label: "Notes/Comments",
      description: "Additional observations or special handling notes",
      example: "Sample received in excellent condition, frozen at -80C",
    },
  ],
  autoGenerated: [
    {
      key: "systemAssignedSampleId",
      label: "System Assigned Sample ID",
      description: "System-generated laboratory sample ID",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier",
    },
  ],
};

/**
 * GBDManifestImportModal - CSV import modal for GBD genomic workflow.
 * Supports mapping genomic-specific reception and processing metadata columns.
 */
function GBDManifestImportModal({ open, onClose, entryId, onImportSuccess }) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    // Required fields
    sampleIdColumn: "",
    sampleTypeColumn: "",
    sourceColumn: "",
    collectionDateColumn: "",
    receptionDateTimeColumn: "",
    // Optional reception metadata
    projectStudyAssociationColumn: "",
    volumeConcentrationColumn: "",
    a260_280Column: "",
    a260_230Column: "",
    rinColumn: "",
    // Optional processing metadata
    extractionMethodKitColumn: "",
    pcrProtocolColumn: "",
    libraryPrepProtocolColumn: "",
    sequencingPlatformColumn: "",
    runIdColumn: "",
    operatorColumn: "",
    processingDateTimeColumn: "",
    notesColumn: "",
  });

  const [step, setStep] = useState(1);
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Dynamic sample types from backend
  const [validSampleTypes, setValidSampleTypes] = useState([]);
  const [isSampleTypesLoading, setIsSampleTypesLoading] = useState(false);

  // Fetch valid sample types from backend when modal opens
  useEffect(() => {
    if (open) {
      setIsSampleTypesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/gbd/sample-types`, {
        method: "GET",
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.sampleTypes) {
            setValidSampleTypes(data.sampleTypes.map((st) => st.description));
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample types:", error);
          // Fallback to empty array - validation will still happen on backend
          setValidSampleTypes([]);
        })
        .finally(() => {
          setIsSampleTypesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   * Matches against expected column keys (case-insensitive).
   */
  const autoMapColumns = useCallback((headers) => {
    // Map of expected column keys to their form field names
    const columnKeyToField = {
      sampleid: "sampleIdColumn",
      sample_id: "sampleIdColumn",
      "sample id": "sampleIdColumn",
      sampletype: "sampleTypeColumn",
      sample_type: "sampleTypeColumn",
      "sample type": "sampleTypeColumn",
      type: "sampleTypeColumn",
      source: "sourceColumn",
      origin: "sourceColumn",
      facility: "sourceColumn",
      studysite: "sourceColumn",
      collectiondate: "collectionDateColumn",
      collection_date: "collectionDateColumn",
      "collection date": "collectionDateColumn",
      collecteddate: "collectionDateColumn",
      receptiondatetime: "receptionDateTimeColumn",
      reception_datetime: "receptionDateTimeColumn",
      "reception date time": "receptionDateTimeColumn",
      receptiondate: "receptionDateTimeColumn",
      receiveddate: "receptionDateTimeColumn",
      projectstudyassociation: "projectStudyAssociationColumn",
      project_study: "projectStudyAssociationColumn",
      projectname: "projectStudyAssociationColumn",
      project: "projectStudyAssociationColumn",
      volumeconcentration: "volumeConcentrationColumn",
      volume_concentration: "volumeConcentrationColumn",
      volume: "volumeConcentrationColumn",
      concentration: "volumeConcentrationColumn",
      a260_280: "a260_280Column",
      "a260/280": "a260_280Column",
      a260280: "a260_280Column",
      a260_230: "a260_230Column",
      "a260/230": "a260_230Column",
      a260230: "a260_230Column",
      rin: "rinColumn",
      rinnumber: "rinColumn",
      extractionmethodkit: "extractionMethodKitColumn",
      extraction_method: "extractionMethodKitColumn",
      extractionkit: "extractionMethodKitColumn",
      pcrprotocol: "pcrProtocolColumn",
      pcr_protocol: "pcrProtocolColumn",
      pcr: "pcrProtocolColumn",
      libraryprep: "libraryPrepProtocolColumn",
      library_prep_protocol: "libraryPrepProtocolColumn",
      sequencingplatform: "sequencingPlatformColumn",
      sequencing_platform: "sequencingPlatformColumn",
      sequencer: "sequencingPlatformColumn",
      platform: "sequencingPlatformColumn",
      runid: "runIdColumn",
      run_id: "runIdColumn",
      "run id": "runIdColumn",
      operator: "operatorColumn",
      technician: "operatorColumn",
      analyst: "operatorColumn",
      processingdatetime: "processingDateTimeColumn",
      processing_datetime: "processingDateTimeColumn",
      "processing date time": "processingDateTimeColumn",
      processingdate: "processingDateTimeColumn",
      notes: "notesColumn",
      comments: "notesColumn",
      remarks: "notesColumn",
    };

    const newMapping = {
      sampleIdColumn: "",
      sampleTypeColumn: "",
      sourceColumn: "",
      collectionDateColumn: "",
      receptionDateTimeColumn: "",
      projectStudyAssociationColumn: "",
      volumeConcentrationColumn: "",
      a260_280Column: "",
      a260_230Column: "",
      rinColumn: "",
      extractionMethodKitColumn: "",
      pcrProtocolColumn: "",
      libraryPrepProtocolColumn: "",
      sequencingPlatformColumn: "",
      runIdColumn: "",
      operatorColumn: "",
      processingDateTimeColumn: "",
      notesColumn: "",
    };

    headers.forEach((header) => {
      // Normalize header: lowercase, remove spaces/underscores/hyphens
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_-]/g, "")
        .replace(/[/\\]/g, "");

      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  }, []);

  const handleFileAdded = useCallback(
    (event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.gbd.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);

        // Auto-map columns based on header names
        const autoMappedColumns = autoMapColumns(headers);
        setColumnMapping(autoMappedColumns);

        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  const handleRemoveFile = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      sampleIdColumn: "",
      sampleTypeColumn: "",
      sourceColumn: "",
      collectionDateColumn: "",
      receptionDateTimeColumn: "",
      projectStudyAssociationColumn: "",
      volumeConcentrationColumn: "",
      a260_280Column: "",
      a260_230Column: "",
      rinColumn: "",
      extractionMethodKitColumn: "",
      pcrProtocolColumn: "",
      libraryPrepProtocolColumn: "",
      sequencingPlatformColumn: "",
      runIdColumn: "",
      operatorColumn: "",
      processingDateTimeColumn: "",
      notesColumn: "",
    });
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  };

  const handleMappingChange = (field, value) => {
    setColumnMapping((prev) => ({ ...prev, [field]: value }));
  };

  // All 5 required fields must be mapped
  const requiredColumnsMapped =
    columnMapping.sampleIdColumn &&
    columnMapping.sampleTypeColumn &&
    columnMapping.sourceColumn &&
    columnMapping.collectionDateColumn &&
    columnMapping.receptionDateTimeColumn;

  const buildFormData = () => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    return formData;
  };

  const handlePreview = async () => {
    if (!file || !entryId) return;
    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/gbd/entry/${entryId}/samples/preview-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message: data.error || "Preview failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) return;
    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/gbd/entry/${entryId}/samples/import-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message: data.error || "Import failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    handleRemoveFile();
    onClose();
  };

  const mappingField = (field, labelId) => (
    <Select
      id={`mapping-${field}`}
      labelText={intl.formatMessage({ id: labelId })}
      value={columnMapping[field]}
      onChange={(e) => handleMappingChange(field, e.target.value)}
    >
      <SelectItem value="" text={intl.formatMessage({ id: "label.select" })} />
      {csvHeaders.map((header) => (
        <SelectItem key={header} value={header} text={header} />
      ))}
    </Select>
  );

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.gbd.manifest.title",
        defaultMessage: "Import GBD Samples from Manifest",
      })}
      primaryButtonText={
        step === 1
          ? intl.formatMessage({ id: "label.button.next" })
          : step === 2
            ? intl.formatMessage({ id: "notebook.manifest.preview" })
            : step === 3
              ? intl.formatMessage({ id: "notebook.manifest.import" })
              : intl.formatMessage({ id: "label.button.close" })
      }
      secondaryButtonText={
        step > 1 && step < 4
          ? intl.formatMessage({ id: "label.button.back" })
          : null
      }
      onRequestSubmit={() => {
        if (step === 1 && file) setStep(2);
        else if (step === 2) handlePreview();
        else if (step === 3) handleImport();
        else handleClose();
      }}
      onSecondarySubmit={() => setStep(step - 1)}
      primaryButtonDisabled={
        (step === 1 && !file) ||
        (step === 2 && !requiredColumnsMapped) ||
        (step === 3 && previewErrors.length > 0) ||
        isPreviewLoading ||
        isImporting
      }
      size="md"
    >
      <div className="manifest-import-modal">
        {step === 1 && (
          <div className="upload-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.gbd.manifest.step1"
                defaultMessage="Upload a CSV file with genomic sample reception and processing metadata. Review the expected data points below before uploading."
              />
            </p>

            {/* Expected Data Points Section */}
            <Accordion className="expected-datapoints-accordion">
              <AccordionItem
                title={
                  <span className="accordion-title">
                    <Information size={16} />
                    <FormattedMessage
                      id="notebook.gbd.manifest.expectedColumns"
                      defaultMessage="Expected CSV Columns & Data Points"
                    />
                  </span>
                }
                open={!file}
              >
                <div className="datapoints-container">
                  {/* Required Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title required-title">
                      <FormattedMessage
                        id="notebook.gbd.manifest.requiredFields"
                        defaultMessage="Required Fields"
                      />
                      <Tag type="red" size="sm">
                        {EXPECTED_DATA_POINTS.required.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Sample Type Field (Validated) */}
                  <div className="datapoints-section">
                    <h5 className="section-title sampletype-title">
                      <FormattedMessage
                        id="notebook.gbd.manifest.sampleTypeField"
                        defaultMessage="Sample Type (Validated)"
                      />
                      <Tag type="purple" size="sm">
                        1
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="notebook.gbd.manifest.validValues"
                              defaultMessage="Valid Values"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        <StructuredListRow>
                          <StructuredListCell>
                            <strong>
                              {EXPECTED_DATA_POINTS.sampleType.label}
                            </strong>
                            <br />
                            <code className="column-key">
                              {EXPECTED_DATA_POINTS.sampleType.key}
                            </code>
                          </StructuredListCell>
                          <StructuredListCell>
                            {EXPECTED_DATA_POINTS.sampleType.description}
                          </StructuredListCell>
                          <StructuredListCell>
                            <div className="valid-values-list">
                              {isSampleTypesLoading ? (
                                <Loading
                                  small
                                  withOverlay={false}
                                  description="Loading sample types..."
                                />
                              ) : validSampleTypes.length > 0 ? (
                                validSampleTypes.map((value, idx) => (
                                  <Tag key={idx} type="outline" size="sm">
                                    {value}
                                  </Tag>
                                ))
                              ) : (
                                <span className="no-sample-types">
                                  <FormattedMessage
                                    id="notebook.gbd.manifest.noSampleTypes"
                                    defaultMessage="No sample types configured. Contact administrator."
                                  />
                                </span>
                              )}
                            </div>
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Optional Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title optional-title">
                      <FormattedMessage
                        id="notebook.gbd.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                      <Tag type="blue" size="sm">
                        {EXPECTED_DATA_POINTS.optional.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Auto-Generated Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title auto-title">
                      <FormattedMessage
                        id="notebook.gbd.manifest.autoGeneratedFields"
                        defaultMessage="Auto-Generated Fields (Do not include in CSV)"
                      />
                      <Tag type="green" size="sm">
                        {EXPECTED_DATA_POINTS.autoGenerated.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.field"
                              defaultMessage="Field"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.autoGenerated.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {/* File Upload */}
            <div className="file-upload-section">
              {!file ? (
                <FileUploaderDropContainer
                  accept={[".csv"]}
                  labelText={intl.formatMessage({
                    id: "notebook.gbd.manifest.dropzone",
                    defaultMessage:
                      "Drag and drop a CSV file here or click to upload",
                  })}
                  onAddFiles={handleFileAdded}
                />
              ) : (
                <FileUploaderItem
                  name={file.name}
                  status="edit"
                  onDelete={handleRemoveFile}
                />
              )}
            </div>
            {fileError && (
              <InlineNotification
                kind="error"
                title={fileError}
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 2 && (
          <div className="mapping-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.gbd.manifest.step2"
                defaultMessage="Map your CSV columns to the expected genomic sample metadata fields. All required fields (marked with *) must be mapped."
              />
            </p>

            {/* Required Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.gbd.manifest.requiredMappings"
                  defaultMessage="Required Fields"
                />
                <Tag type="red" size="sm">
                  5
                </Tag>
              </h5>
              <div className="mapping-grid">
                <div className="mapping-field required">
                  {mappingField(
                    "sampleIdColumn",
                    "notebook.gbd.manifest.column.sampleId",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "sampleTypeColumn",
                    "notebook.gbd.manifest.column.sampleType",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "sourceColumn",
                    "notebook.gbd.manifest.column.source",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "collectionDateColumn",
                    "notebook.gbd.manifest.column.collectionDate",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "receptionDateTimeColumn",
                    "notebook.gbd.manifest.column.receptionDateTime",
                  )}
                  <span className="required-marker">*</span>
                </div>
              </div>
            </div>

            {/* Sample Type Field Section (Validated) */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.gbd.manifest.sampleTypeMappings"
                  defaultMessage="Sample Type (Validated)"
                />
                <Tag type="purple" size="sm">
                  1
                </Tag>
              </h5>
              <p className="mapping-section-info">
                <FormattedMessage
                  id="notebook.gbd.manifest.sampleTypeInfo"
                  defaultMessage="Sample type must match one of the valid GBD lab types (DNA, RNA, tissue, swabs, isolates, PCR products, libraries). Invalid types will be rejected during validation."
                />
              </p>
              <div className="mapping-grid">
                {mappingField(
                  "sampleTypeColumn",
                  "notebook.gbd.manifest.column.sampleType",
                )}
              </div>
            </div>

            {/* Optional Reception Metadata Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.gbd.manifest.optionalReceptionMappings"
                  defaultMessage="Optional Reception Metadata"
                />
                <Tag type="blue" size="sm">
                  5
                </Tag>
              </h5>
              <div className="mapping-grid">
                {mappingField(
                  "projectStudyAssociationColumn",
                  "notebook.gbd.manifest.column.projectStudyAssociation",
                )}
                {mappingField(
                  "volumeConcentrationColumn",
                  "notebook.gbd.manifest.column.volumeConcentration",
                )}
                {mappingField(
                  "a260_280Column",
                  "notebook.gbd.manifest.column.a260_280",
                )}
                {mappingField(
                  "a260_230Column",
                  "notebook.gbd.manifest.column.a260_230",
                )}
                {mappingField("rinColumn", "notebook.gbd.manifest.column.rin")}
              </div>
            </div>

            {/* Optional Processing Metadata Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.gbd.manifest.optionalProcessingMappings"
                  defaultMessage="Optional Processing Metadata"
                />
                <Tag type="blue" size="sm">
                  8
                </Tag>
              </h5>
              <div className="mapping-grid">
                {mappingField(
                  "extractionMethodKitColumn",
                  "notebook.gbd.manifest.column.extractionMethodKit",
                )}
                {mappingField(
                  "pcrProtocolColumn",
                  "notebook.gbd.manifest.column.pcrProtocol",
                )}
                {mappingField(
                  "libraryPrepProtocolColumn",
                  "notebook.gbd.manifest.column.libraryPrepProtocol",
                )}
                {mappingField(
                  "sequencingPlatformColumn",
                  "notebook.gbd.manifest.column.sequencingPlatform",
                )}
                {mappingField(
                  "runIdColumn",
                  "notebook.gbd.manifest.column.runId",
                )}
                {mappingField(
                  "operatorColumn",
                  "notebook.gbd.manifest.column.operator",
                )}
                {mappingField(
                  "processingDateTimeColumn",
                  "notebook.gbd.manifest.column.processingDateTime",
                )}
                {mappingField(
                  "notesColumn",
                  "notebook.gbd.manifest.column.notes",
                )}
              </div>
            </div>

            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 3 && (
          <div className="preview-step">
            {isPreviewLoading ? (
              <Loading withOverlay={false} description="Loading preview..." />
            ) : (
              <>
                {previewErrors.length > 0 && (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={
                      <ul className="error-list">
                        {previewErrors.map((error, idx) => (
                          <li key={idx}>
                            {error.rowNumber > 0
                              ? `Row ${error.rowNumber}: `
                              : ""}
                            {error.message}
                          </li>
                        ))}
                      </ul>
                    }
                    lowContrast
                    hideCloseButton
                  />
                )}

                {previewData && previewErrors.length === 0 && (
                  <div className="preview-summary">
                    <Tag type="blue">
                      <FormattedMessage
                        id="notebook.manifest.preview.rows"
                        defaultMessage="{count} rows"
                        values={{ count: previewData.totalRows }}
                      />
                    </Tag>
                    <Tag type="green">
                      <FormattedMessage
                        id="notebook.manifest.preview.samples"
                        defaultMessage="{count} samples to create"
                        values={{ count: previewData.totalSamplesToCreate }}
                      />
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {step === 4 && (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h3>
              <FormattedMessage
                id="notebook.manifest.success.title"
                defaultMessage="Import Successful"
              />
            </h3>
            <p>
              <FormattedMessage
                id="notebook.gbd.manifest.success.message"
                defaultMessage="GBD samples have been created and linked to the notebook entry with genomic metadata."
              />
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default GBDManifestImportModal;
