import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
} from "@carbon/react";
import { Upload, Checkmark, Warning, Information } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for Pharmaceutical Sample Import Manifest.
 * Aligned with Liquibase schema: 012-pharmaceuticals-notebook-template.xml
 * Note: sampleType.validValues is now fetched dynamically from the backend API
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "sampleName",
      label: "Sample Name",
      description: "Name/description of the sample",
      example: "Paracetamol 500mg Tablets",
    },
    {
      key: "lotBatchNumber",
      label: "Lot/Batch Number",
      description: "Manufacturing lot or batch identifier",
      example: "LOT-2024-001",
    },
    {
      key: "dateOfManufacture",
      label: "Date of Manufacture",
      description: "Manufacturing date (YYYY-MM-DD)",
      example: "2024-01-15",
    },
    {
      key: "expiryRetestDate",
      label: "Expiry/Re-test Date",
      description: "Expiration or re-test date (YYYY-MM-DD)",
      example: "2027-01-14",
    },
    {
      key: "storageCondition",
      label: "Storage Condition",
      description:
        "Required storage temperature/conditions (Controlled Room Temp, Refrigerated, Frozen, Deep Frozen, Liquid Nitrogen, Ambient, Other)",
      example: "Controlled Room Temp (15-25C)",
    },
    {
      key: "ownerRequester",
      label: "Owner/Requester",
      description: "Organization or individual requesting analysis",
      example: "ABC Pharmaceuticals Ltd",
    },
  ],
  sampleType: {
    key: "sampleType",
    label: "Sample Type",
    description:
      "Type of pharmaceutical sample (validated against Pharmaceutical lab types)",
    example: "Tablets, Capsules, API, Injections, etc.",
  },
  optional: [
    {
      key: "alphanumericCode",
      label: "Alphanumeric Code",
      description: "External reference code (sponsor code, internal ID)",
      example: "PAR-500-001",
    },
    {
      key: "chemicalIupacName",
      label: "Chemical/IUPAC Name",
      description: "Systematic chemical nomenclature",
      example: "N-(4-hydroxyphenyl)acetamide",
    },
    {
      key: "gradeSpecification",
      label: "Grade/Specification",
      description: "Purity grade or quality specification",
      example: "USP, BP, IP, Ph.Eur.",
    },
    {
      key: "chainOfCustodyDetails",
      label: "Chain of Custody Details",
      description: "Custody transfer history and handling notes",
      example: "Received from warehouse at 09:00 AM",
    },
    {
      key: "patientId",
      label: "Patient ID",
      description: "For clinical samples only",
      example: "PT-12345",
    },
    {
      key: "clinicalTrialNumber",
      label: "Clinical Trial Number",
      description: "Protocol or trial identifier (e.g., NCT number)",
      example: "NCT04567890",
    },
    {
      key: "consentStatus",
      label: "Consent Status",
      description: "Consent status for clinical samples",
      example: "Obtained, Pending, Waived, Not Applicable",
    },
  ],
  autoGenerated: [
    {
      key: "uniqueSampleId",
      label: "Unique Sample ID",
      description: "System-generated unique identifier",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier",
    },
  ],
};

/**
 * PharmaManifestImportModal - CSV import modal for Pharmaceuticals workflow.
 * Supports mapping pharma-specific columns aligned with the updated dataPoints schema.
 */
function PharmaManifestImportModal({
  open,
  onClose,
  entryId,
  onImportSuccess,
}) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    // Required fields
    sampleNameColumn: "",
    lotBatchNumberColumn: "",
    dateOfManufactureColumn: "",
    expiryRetestDateColumn: "",
    storageConditionColumn: "",
    ownerRequesterColumn: "",
    // Sample type (validated against Pharmaceutical lab types)
    sampleTypeColumn: "",
    // Optional fields
    alphanumericCodeColumn: "",
    chemicalIupacNameColumn: "",
    gradeSpecificationColumn: "",
    chainOfCustodyDetailsColumn: "",
    patientIdColumn: "",
    clinicalTrialNumberColumn: "",
    consentStatusColumn: "",
  });

  const [step, setStep] = useState(1);
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Dynamic sample types from backend
  const [validSampleTypes, setValidSampleTypes] = useState([]);
  const [isSampleTypesLoading, setIsSampleTypesLoading] = useState(false);

  // Fetch valid sample types from backend when modal opens
  useEffect(() => {
    if (open) {
      setIsSampleTypesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/pharma/sample-types`, {
        method: "GET",
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.sampleTypes) {
            setValidSampleTypes(data.sampleTypes.map((st) => st.description));
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample types:", error);
          // Fallback to empty array - validation will still happen on backend
          setValidSampleTypes([]);
        })
        .finally(() => {
          setIsSampleTypesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   * Matches against expected column keys (case-insensitive).
   */
  const autoMapColumns = useCallback((headers) => {
    // Map of expected column keys to their form field names
    const columnKeyToField = {
      samplename: "sampleNameColumn",
      lotbatchnumber: "lotBatchNumberColumn",
      dateofmanufacture: "dateOfManufactureColumn",
      expiryretestdate: "expiryRetestDateColumn",
      storagecondition: "storageConditionColumn",
      ownerrequester: "ownerRequesterColumn",
      sampletype: "sampleTypeColumn",
      alphanumericcode: "alphanumericCodeColumn",
      chemicaliupacname: "chemicalIupacNameColumn",
      gradespecification: "gradeSpecificationColumn",
      chainofcustodydetails: "chainOfCustodyDetailsColumn",
      patientid: "patientIdColumn",
      clinicaltrialnumber: "clinicalTrialNumberColumn",
      consentstatus: "consentStatusColumn",
    };

    const newMapping = {
      sampleNameColumn: "",
      lotBatchNumberColumn: "",
      dateOfManufactureColumn: "",
      expiryRetestDateColumn: "",
      storageConditionColumn: "",
      ownerRequesterColumn: "",
      sampleTypeColumn: "",
      alphanumericCodeColumn: "",
      chemicalIupacNameColumn: "",
      gradeSpecificationColumn: "",
      chainOfCustodyDetailsColumn: "",
      patientIdColumn: "",
      clinicalTrialNumberColumn: "",
      consentStatusColumn: "",
    };

    headers.forEach((header) => {
      // Normalize header: lowercase, remove spaces/underscores/hyphens
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_-]/g, "")
        .replace(/[/\\]/g, "");

      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  }, []);

  const handleFileAdded = useCallback(
    (event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.pharma.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);

        // Auto-map columns based on header names
        const autoMappedColumns = autoMapColumns(headers);
        setColumnMapping(autoMappedColumns);

        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  const handleRemoveFile = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      // Required fields
      sampleNameColumn: "",
      lotBatchNumberColumn: "",
      dateOfManufactureColumn: "",
      expiryRetestDateColumn: "",
      storageConditionColumn: "",
      ownerRequesterColumn: "",
      // Sample type (validated against Pharmaceutical lab types)
      sampleTypeColumn: "",
      // Optional fields
      alphanumericCodeColumn: "",
      chemicalIupacNameColumn: "",
      gradeSpecificationColumn: "",
      chainOfCustodyDetailsColumn: "",
      patientIdColumn: "",
      clinicalTrialNumberColumn: "",
      consentStatusColumn: "",
    });
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  };

  const handleMappingChange = (field, value) => {
    setColumnMapping((prev) => ({ ...prev, [field]: value }));
  };

  // All 6 required fields must be mapped
  const requiredColumnsMapped =
    columnMapping.sampleNameColumn &&
    columnMapping.lotBatchNumberColumn &&
    columnMapping.dateOfManufactureColumn &&
    columnMapping.expiryRetestDateColumn &&
    columnMapping.storageConditionColumn &&
    columnMapping.ownerRequesterColumn;

  const buildFormData = () => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    return formData;
  };

  const handlePreview = async () => {
    if (!file || !entryId) return;
    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/pharma/entry/${entryId}/samples/preview-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message: data.error || "Preview failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) return;
    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/pharma/entry/${entryId}/samples/create-from-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message: data.error || "Import failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    handleRemoveFile();
    onClose();
  };

  const mappingField = (field, labelId) => (
    <Select
      id={`mapping-${field}`}
      labelText={intl.formatMessage({ id: labelId })}
      value={columnMapping[field]}
      onChange={(e) => handleMappingChange(field, e.target.value)}
    >
      <SelectItem value="" text={intl.formatMessage({ id: "label.select" })} />
      {csvHeaders.map((header) => (
        <SelectItem key={header} value={header} text={header} />
      ))}
    </Select>
  );

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.pharma.manifest.title",
        defaultMessage: "Import Pharmaceutical Samples from Manifest",
      })}
      primaryButtonText={
        step === 1
          ? intl.formatMessage({ id: "label.button.next", defaultMessage: "Next" })
          : step === 2
            ? intl.formatMessage({ id: "notebook.manifest.preview", defaultMessage: "Preview" })
            : step === 3
              ? intl.formatMessage({ id: "notebook.manifest.import", defaultMessage: "Import" })
              : intl.formatMessage({ id: "label.button.close", defaultMessage: "Close" })
      }
      secondaryButtonText={
        step > 1 && step < 4
          ? intl.formatMessage({ id: "label.button.back", defaultMessage: "Back" })
          : null
      }
      onRequestSubmit={() => {
        if (step === 1 && file) setStep(2);
        else if (step === 2) handlePreview();
        else if (step === 3) handleImport();
        else handleClose();
      }}
      onSecondarySubmit={() => setStep(step - 1)}
      primaryButtonDisabled={
        (step === 1 && !file) ||
        (step === 2 && !requiredColumnsMapped) ||
        (step === 3 && previewErrors.length > 0) ||
        isPreviewLoading ||
        isImporting
      }
      size="lg"
    >
      <div className="manifest-import-modal">
        {step === 1 && (
          <div className="upload-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.pharma.manifest.step1"
                defaultMessage="Upload a CSV file with pharmaceutical sample metadata. Review the expected data points below before uploading."
              />
            </p>

            {/* Expected Data Points Section */}
            <Accordion className="expected-datapoints-accordion">
              <AccordionItem
                title={
                  <span className="accordion-title">
                    <Information size={16} />
                    <FormattedMessage
                      id="notebook.pharma.manifest.expectedColumns"
                      defaultMessage="Expected CSV Columns & Data Points"
                    />
                  </span>
                }
                open={!file}
              >
                <div className="datapoints-container">
                  {/* Required Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title required-title">
                      <FormattedMessage
                        id="notebook.pharma.manifest.requiredFields"
                        defaultMessage="Required Fields"
                      />
                      <Tag type="red" size="sm">
                        {EXPECTED_DATA_POINTS.required.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Sample Type Field (Validated) */}
                  <div className="datapoints-section">
                    <h5 className="section-title sampletype-title">
                      <FormattedMessage
                        id="notebook.pharma.manifest.sampleTypeField"
                        defaultMessage="Sample Type (Validated)"
                      />
                      <Tag type="purple" size="sm">
                        1
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="notebook.pharma.manifest.validValues"
                              defaultMessage="Valid Values"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        <StructuredListRow>
                          <StructuredListCell>
                            <strong>
                              {EXPECTED_DATA_POINTS.sampleType.label}
                            </strong>
                            <br />
                            <code className="column-key">
                              {EXPECTED_DATA_POINTS.sampleType.key}
                            </code>
                          </StructuredListCell>
                          <StructuredListCell>
                            {EXPECTED_DATA_POINTS.sampleType.description}
                          </StructuredListCell>
                          <StructuredListCell>
                            <div className="valid-values-list">
                              {isSampleTypesLoading ? (
                                <Loading
                                  small
                                  withOverlay={false}
                                  description="Loading sample types..."
                                />
                              ) : validSampleTypes.length > 0 ? (
                                validSampleTypes.map((value, idx) => (
                                  <Tag key={idx} type="outline" size="sm">
                                    {value}
                                  </Tag>
                                ))
                              ) : (
                                <span className="no-sample-types">
                                  <FormattedMessage
                                    id="notebook.pharma.manifest.noSampleTypes"
                                    defaultMessage="No sample types configured. Contact administrator."
                                  />
                                </span>
                              )}
                            </div>
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Optional Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title optional-title">
                      <FormattedMessage
                        id="notebook.pharma.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                      <Tag type="blue" size="sm">
                        {EXPECTED_DATA_POINTS.optional.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Auto-Generated Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title auto-title">
                      <FormattedMessage
                        id="notebook.pharma.manifest.autoGeneratedFields"
                        defaultMessage="Auto-Generated Fields (Do not include in CSV)"
                      />
                      <Tag type="green" size="sm">
                        {EXPECTED_DATA_POINTS.autoGenerated.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.field"
                              defaultMessage="Field"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.autoGenerated.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {/* File Upload */}
            <div className="file-upload-section">
              {!file ? (
                <FileUploaderDropContainer
                  accept={[".csv"]}
                  labelText={intl.formatMessage({
                    id: "notebook.pharma.manifest.dropzone",
                    defaultMessage:
                      "Drag and drop a CSV file here or click to upload",
                  })}
                  onAddFiles={handleFileAdded}
                />
              ) : (
                <FileUploaderItem
                  name={file.name}
                  status="edit"
                  onDelete={handleRemoveFile}
                />
              )}
            </div>
            {fileError && (
              <InlineNotification
                kind="error"
                title={fileError}
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 2 && (
          <div className="mapping-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.pharma.manifest.step2"
                defaultMessage="Map your CSV columns to the expected sample metadata fields. All required fields (marked with *) must be mapped."
              />
            </p>

            {/* Required Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.pharma.manifest.requiredMappings"
                  defaultMessage="Required Fields"
                />
                <Tag type="red" size="sm">
                  6
                </Tag>
              </h5>
              <div className="mapping-grid">
                <div className="mapping-field required">
                  {mappingField(
                    "sampleNameColumn",
                    "notebook.pharma.manifest.column.sampleName",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "lotBatchNumberColumn",
                    "notebook.pharma.manifest.column.lotBatchNumber",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "dateOfManufactureColumn",
                    "notebook.pharma.manifest.column.dateOfManufacture",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "expiryRetestDateColumn",
                    "notebook.pharma.manifest.column.expiryRetestDate",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "storageConditionColumn",
                    "notebook.pharma.manifest.column.storageCondition",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "ownerRequesterColumn",
                    "notebook.pharma.manifest.column.ownerRequester",
                  )}
                  <span className="required-marker">*</span>
                </div>
              </div>
            </div>

            {/* Sample Type Field Section (Validated) */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.pharma.manifest.sampleTypeMappings"
                  defaultMessage="Sample Type (Validated)"
                />
                <Tag type="purple" size="sm">
                  1
                </Tag>
              </h5>
              <p className="mapping-section-info">
                <FormattedMessage
                  id="notebook.pharma.manifest.sampleTypeInfo"
                  defaultMessage="Sample type must match one of the valid Pharmaceutical lab types. Invalid types will be rejected during validation."
                />
              </p>
              <div className="mapping-grid">
                {mappingField(
                  "sampleTypeColumn",
                  "notebook.pharma.manifest.column.sampleType",
                )}
              </div>
            </div>

            {/* Optional Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.pharma.manifest.optionalMappings"
                  defaultMessage="Optional Fields"
                />
                <Tag type="blue" size="sm">
                  7
                </Tag>
              </h5>
              <div className="mapping-grid">
                {mappingField(
                  "alphanumericCodeColumn",
                  "notebook.pharma.manifest.column.alphanumericCode",
                )}
                {mappingField(
                  "chemicalIupacNameColumn",
                  "notebook.pharma.manifest.column.chemicalIupacName",
                )}
                {mappingField(
                  "gradeSpecificationColumn",
                  "notebook.pharma.manifest.column.gradeSpecification",
                )}
                {mappingField(
                  "chainOfCustodyDetailsColumn",
                  "notebook.pharma.manifest.column.chainOfCustodyDetails",
                )}
                {mappingField(
                  "patientIdColumn",
                  "notebook.pharma.manifest.column.patientId",
                )}
                {mappingField(
                  "clinicalTrialNumberColumn",
                  "notebook.pharma.manifest.column.clinicalTrialNumber",
                )}
                {mappingField(
                  "consentStatusColumn",
                  "notebook.pharma.manifest.column.consentStatus",
                )}
              </div>
            </div>

            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 3 && (
          <div className="preview-step">
            {isPreviewLoading ? (
              <Loading withOverlay={false} description="Loading preview..." />
            ) : (
              <>
                {previewErrors.length > 0 && (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={
                      <ul className="error-list">
                        {previewErrors.map((error, idx) => (
                          <li key={idx}>
                            {error.rowNumber > 0
                              ? `Row ${error.rowNumber}: `
                              : ""}
                            {error.message}
                          </li>
                        ))}
                      </ul>
                    }
                    lowContrast
                    hideCloseButton
                  />
                )}

                {previewData && previewErrors.length === 0 && (
                  <div className="preview-summary">
                    <Tag type="blue">
                      <FormattedMessage
                        id="notebook.manifest.preview.rows"
                        defaultMessage="{count} rows"
                        values={{ count: previewData.totalRows }}
                      />
                    </Tag>
                    <Tag type="green">
                      <FormattedMessage
                        id="notebook.manifest.preview.samples"
                        defaultMessage="{count} samples to create"
                        values={{ count: previewData.totalSamplesToCreate }}
                      />
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {step === 4 && (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h3>
              <FormattedMessage
                id="notebook.manifest.success.title"
                defaultMessage="Import Successful"
              />
            </h3>
            <p>
              <FormattedMessage
                id="notebook.manifest.success.message"
                defaultMessage="Samples have been created and linked to the notebook entry."
              />
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default PharmaManifestImportModal;
