import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
} from "@carbon/react";
import { Upload, Checkmark, Warning, Information } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for Virology & Vaccine Unit Sample Reception Manifest.
 * Aligned with the virology workflow reception metadata requirements from PDF spec.
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "sampleId",
      label: "Sample ID",
      description: "Unique identifier for the sample",
      example: "VIR-2024-001",
    },
    {
      key: "source",
      label: "Source",
      description:
        "Origin of the sample (patient, animal model, environmental, production batch)",
      example: "Patient",
    },
    {
      key: "sampleType",
      label: "Sample Type",
      description:
        "Type of virology sample (validated against Virology lab types)",
      example: "Nasal Swab, Throat Swab, Viral Isolate, etc.",
    },
    {
      key: "receptionDateTime",
      label: "Reception Date & Time",
      description:
        "Date and time of sample reception (YYYY-MM-DD HH:MM or 'now')",
      example: "2024-01-16 14:00",
    },
    {
      key: "testType",
      label: "Test Type",
      description: "Type of testing to be performed (viral vs. bacterial)",
      example: "Viral, Bacterial",
    },
    {
      key: "projectStudyAssociation",
      label: "Project/Study Association",
      description: "Associated project or study identifier",
      example: "COVID-VAC-2024",
    },
  ],
  virusVaccineProduction: [
    {
      key: "batchId",
      label: "Batch ID",
      description: "Production batch identifier",
      example: "BATCH-2024-001",
    },
    {
      key: "productionStage",
      label: "Production Stage",
      description: "Current stage in production workflow",
      example: "Cell Culture, Virus Culture, Formulation",
    },
    {
      key: "cellLineUsed",
      label: "Cell Line Used",
      description: "Cell line used for culture",
      example: "Vero, HEK293, MDCK",
    },
    {
      key: "passageNumber",
      label: "Passage Number",
      description: "Current passage number",
      example: "P3, 5",
    },
    {
      key: "titerValues",
      label: "Titer Values",
      description: "Viral titer measurements",
      example: "1x10^6 TCID50/mL",
    },
    {
      key: "qualityControlResults",
      label: "Quality Control Results",
      description: "QC test results",
      example: "Pass, Fail, Pending",
    },
    {
      key: "formulationDetails",
      label: "Formulation Details",
      description: "Vaccine formulation information",
      example: "Adjuvant type, concentration",
    },
  ],
  optional: [
    {
      key: "collectionDateTime",
      label: "Collection Date & Time",
      description: "Date and time of sample collection (YYYY-MM-DD HH:MM)",
      example: "2024-01-15 09:30",
    },
    {
      key: "storageConditionOnArrival",
      label: "Storage Condition on Arrival",
      description:
        "Storage condition when received (Ambient, Refrigerated, Frozen, etc.)",
      example: "Frozen (-80C)",
    },
    {
      key: "transportTemperature",
      label: "Transport Temperature",
      description: "Temperature during transport (in Celsius)",
      example: "4C, -20C, -80C",
    },
    {
      key: "receivingPersonnelName",
      label: "Receiving Personnel Name",
      description: "Name of person who received the sample",
      example: "Dr. Teklu Abebe",
    },
    {
      key: "manifestVerificationStatus",
      label: "Manifest Verification Status",
      description:
        "Status of manifest verification (Verified, Pending, Discrepancy)",
      example: "Verified",
    },
    {
      key: "notes",
      label: "Notes/Comments",
      description: "Additional notes or observations",
      example: "Sample received in good condition",
    },
  ],
  autoGenerated: [
    {
      key: "accessionNumber",
      label: "Accession Number",
      description: "System-generated laboratory accession number",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier",
    },
  ],
};

/**
 * VirologyManifestImportModal - CSV import modal for Virology & Vaccine Unit workflow.
 * Supports mapping virology-specific reception metadata columns.
 */
function VirologyManifestImportModal({
  open,
  onClose,
  entryId,
  onImportSuccess,
}) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    // Required fields - Sample Arrival
    sampleIdColumn: "",
    sourceColumn: "",
    sampleTypeColumn: "",
    receptionDateTimeColumn: "",
    testTypeColumn: "",
    projectStudyAssociationColumn: "",
    // Virus/Vaccine Production fields
    batchIdColumn: "",
    productionStageColumn: "",
    cellLineUsedColumn: "",
    passageNumberColumn: "",
    titerValuesColumn: "",
    qualityControlResultsColumn: "",
    formulationDetailsColumn: "",
    // Optional fields
    collectionDateTimeColumn: "",
    storageConditionOnArrivalColumn: "",
    transportTemperatureColumn: "",
    receivingPersonnelNameColumn: "",
    manifestVerificationStatusColumn: "",
    notesColumn: "",
  });

  const [step, setStep] = useState(1);
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Dynamic sample types from backend
  const [validSampleTypes, setValidSampleTypes] = useState([]);
  const [isSampleTypesLoading, setIsSampleTypesLoading] = useState(false);

  // Fetch valid sample types from backend when modal opens
  useEffect(() => {
    if (open) {
      setIsSampleTypesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/virology/sample-types`, {
        method: "GET",
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.sampleTypes) {
            setValidSampleTypes(data.sampleTypes.map((st) => st.description));
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample types:", error);
          setValidSampleTypes([]);
        })
        .finally(() => {
          setIsSampleTypesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   */
  const autoMapColumns = useCallback((headers) => {
    const columnKeyToField = {
      // Sample Arrival fields
      sampleid: "sampleIdColumn",
      sample_id: "sampleIdColumn",
      id: "sampleIdColumn",
      source: "sourceColumn",
      origin: "sourceColumn",
      sampletype: "sampleTypeColumn",
      sample_type: "sampleTypeColumn",
      type: "sampleTypeColumn",
      receptiondatetime: "receptionDateTimeColumn",
      reception_date_time: "receptionDateTimeColumn",
      receptiondate: "receptionDateTimeColumn",
      received_date: "receptionDateTimeColumn",
      testtype: "testTypeColumn",
      test_type: "testTypeColumn",
      test: "testTypeColumn",
      projectstudyassociation: "projectStudyAssociationColumn",
      project_study_association: "projectStudyAssociationColumn",
      project: "projectStudyAssociationColumn",
      study: "projectStudyAssociationColumn",
      // Virus/Vaccine Production fields
      batchid: "batchIdColumn",
      batch_id: "batchIdColumn",
      batch: "batchIdColumn",
      productionstage: "productionStageColumn",
      production_stage: "productionStageColumn",
      stage: "productionStageColumn",
      celllineused: "cellLineUsedColumn",
      cell_line_used: "cellLineUsedColumn",
      cellline: "cellLineUsedColumn",
      cell_line: "cellLineUsedColumn",
      passagenumber: "passageNumberColumn",
      passage_number: "passageNumberColumn",
      passage: "passageNumberColumn",
      titervalues: "titerValuesColumn",
      titer_values: "titerValuesColumn",
      titer: "titerValuesColumn",
      qualitycontrolresults: "qualityControlResultsColumn",
      quality_control_results: "qualityControlResultsColumn",
      qc_results: "qualityControlResultsColumn",
      qc: "qualityControlResultsColumn",
      formulationdetails: "formulationDetailsColumn",
      formulation_details: "formulationDetailsColumn",
      formulation: "formulationDetailsColumn",
      // Optional fields
      collectiondatetime: "collectionDateTimeColumn",
      collection_date_time: "collectionDateTimeColumn",
      collectiondate: "collectionDateTimeColumn",
      collection_date: "collectionDateTimeColumn",
      storageconditiononarrival: "storageConditionOnArrivalColumn",
      storage_condition_on_arrival: "storageConditionOnArrivalColumn",
      storagecondition: "storageConditionOnArrivalColumn",
      storage_condition: "storageConditionOnArrivalColumn",
      storage: "storageConditionOnArrivalColumn",
      transporttemperature: "transportTemperatureColumn",
      transport_temperature: "transportTemperatureColumn",
      temperature: "transportTemperatureColumn",
      temp: "transportTemperatureColumn",
      receivingpersonnelname: "receivingPersonnelNameColumn",
      receiving_personnel_name: "receivingPersonnelNameColumn",
      receivedby: "receivingPersonnelNameColumn",
      received_by: "receivingPersonnelNameColumn",
      receiver: "receivingPersonnelNameColumn",
      manifestverificationstatus: "manifestVerificationStatusColumn",
      manifest_verification_status: "manifestVerificationStatusColumn",
      verificationstatus: "manifestVerificationStatusColumn",
      verification_status: "manifestVerificationStatusColumn",
      verified: "manifestVerificationStatusColumn",
      notes: "notesColumn",
      comments: "notesColumn",
    };

    const newMapping = {
      sampleIdColumn: "",
      sourceColumn: "",
      sampleTypeColumn: "",
      receptionDateTimeColumn: "",
      testTypeColumn: "",
      projectStudyAssociationColumn: "",
      batchIdColumn: "",
      productionStageColumn: "",
      cellLineUsedColumn: "",
      passageNumberColumn: "",
      titerValuesColumn: "",
      qualityControlResultsColumn: "",
      formulationDetailsColumn: "",
      collectionDateTimeColumn: "",
      storageConditionOnArrivalColumn: "",
      transportTemperatureColumn: "",
      receivingPersonnelNameColumn: "",
      manifestVerificationStatusColumn: "",
      notesColumn: "",
    };

    headers.forEach((header) => {
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_-]/g, "")
        .replace(/[/\\]/g, "");

      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  }, []);

  const handleFileAdded = useCallback(
    (event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.virology.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);

        const autoMappedColumns = autoMapColumns(headers);
        setColumnMapping(autoMappedColumns);

        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  const handleRemoveFile = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      sampleIdColumn: "",
      sourceColumn: "",
      sampleTypeColumn: "",
      receptionDateTimeColumn: "",
      testTypeColumn: "",
      projectStudyAssociationColumn: "",
      batchIdColumn: "",
      productionStageColumn: "",
      cellLineUsedColumn: "",
      passageNumberColumn: "",
      titerValuesColumn: "",
      qualityControlResultsColumn: "",
      formulationDetailsColumn: "",
      collectionDateTimeColumn: "",
      storageConditionOnArrivalColumn: "",
      transportTemperatureColumn: "",
      receivingPersonnelNameColumn: "",
      manifestVerificationStatusColumn: "",
      notesColumn: "",
    });
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  };

  const handleMappingChange = (field, value) => {
    setColumnMapping((prev) => ({ ...prev, [field]: value }));
  };

  // All 6 required fields must be mapped
  const requiredColumnsMapped =
    columnMapping.sampleIdColumn &&
    columnMapping.sourceColumn &&
    columnMapping.sampleTypeColumn &&
    columnMapping.receptionDateTimeColumn &&
    columnMapping.testTypeColumn &&
    columnMapping.projectStudyAssociationColumn;

  const buildFormData = () => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    return formData;
  };

  const handlePreview = async () => {
    if (!file || !entryId) return;
    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/virology/entry/${entryId}/samples/preview-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message: data.error || "Preview failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) return;
    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/virology/entry/${entryId}/samples/create-from-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message: data.error || "Import failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    handleRemoveFile();
    onClose();
  };

  const mappingField = (field, labelId) => (
    <Select
      id={`mapping-${field}`}
      labelText={intl.formatMessage({ id: labelId })}
      value={columnMapping[field]}
      onChange={(e) => handleMappingChange(field, e.target.value)}
    >
      <SelectItem value="" text={intl.formatMessage({ id: "label.select" })} />
      {csvHeaders.map((header) => (
        <SelectItem key={header} value={header} text={header} />
      ))}
    </Select>
  );

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.virology.manifest.title",
        defaultMessage: "Import Virology Samples from Delivery Manifest",
      })}
      primaryButtonText={
        step === 1
          ? intl.formatMessage({ id: "label.button.next" })
          : step === 2
            ? intl.formatMessage({ id: "notebook.manifest.preview" })
            : step === 3
              ? intl.formatMessage({ id: "notebook.manifest.import" })
              : intl.formatMessage({ id: "label.button.close" })
      }
      secondaryButtonText={
        step > 1 && step < 4
          ? intl.formatMessage({ id: "label.button.back" })
          : null
      }
      onRequestSubmit={() => {
        if (step === 1 && file) setStep(2);
        else if (step === 2) handlePreview();
        else if (step === 3) handleImport();
        else handleClose();
      }}
      onSecondarySubmit={() => setStep(step - 1)}
      primaryButtonDisabled={
        (step === 1 && !file) ||
        (step === 2 && !requiredColumnsMapped) ||
        (step === 3 && previewErrors.length > 0) ||
        isPreviewLoading ||
        isImporting
      }
      size="lg"
    >
      <div className="manifest-import-modal">
        {step === 1 && (
          <div className="upload-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.virology.manifest.step1"
                defaultMessage="Upload a CSV file with virology sample reception metadata. Review the expected data points below before uploading."
              />
            </p>

            {/* Expected Data Points Section */}
            <Accordion className="expected-datapoints-accordion">
              <AccordionItem
                title={
                  <span className="accordion-title">
                    <Information size={16} />
                    <FormattedMessage
                      id="notebook.virology.manifest.expectedColumns"
                      defaultMessage="Expected CSV Columns & Data Points"
                    />
                  </span>
                }
                open={!file}
              >
                <div className="datapoints-container">
                  {/* Required Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title required-title">
                      <FormattedMessage
                        id="notebook.virology.manifest.requiredFields"
                        defaultMessage="Required Fields - Sample Arrival"
                      />
                      <Tag type="red" size="sm">
                        {EXPECTED_DATA_POINTS.required.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Virus/Vaccine Production Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title sampletype-title">
                      <FormattedMessage
                        id="notebook.virology.manifest.productionFields"
                        defaultMessage="Virus/Vaccine Production Fields"
                      />
                      <Tag type="purple" size="sm">
                        {EXPECTED_DATA_POINTS.virusVaccineProduction.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.virusVaccineProduction.map(
                          (field) => (
                            <StructuredListRow key={field.key}>
                              <StructuredListCell>
                                <strong>{field.label}</strong>
                                <br />
                                <code className="column-key">{field.key}</code>
                              </StructuredListCell>
                              <StructuredListCell>
                                {field.description}
                              </StructuredListCell>
                              <StructuredListCell>
                                <code>{field.example}</code>
                              </StructuredListCell>
                            </StructuredListRow>
                          ),
                        )}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Valid Sample Types */}
                  <div className="datapoints-section">
                    <h5 className="section-title">
                      <FormattedMessage
                        id="notebook.virology.manifest.validSampleTypes"
                        defaultMessage="Valid Sample Types"
                      />
                    </h5>
                    <div className="valid-values-list">
                      {isSampleTypesLoading ? (
                        <Loading
                          small
                          withOverlay={false}
                          description="Loading sample types..."
                        />
                      ) : validSampleTypes.length > 0 ? (
                        validSampleTypes.map((value, idx) => (
                          <Tag key={idx} type="outline" size="sm">
                            {value}
                          </Tag>
                        ))
                      ) : (
                        <span className="no-sample-types">
                          <FormattedMessage
                            id="notebook.virology.manifest.noSampleTypes"
                            defaultMessage="No sample types configured. Contact administrator."
                          />
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Optional Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title optional-title">
                      <FormattedMessage
                        id="notebook.virology.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                      <Tag type="blue" size="sm">
                        {EXPECTED_DATA_POINTS.optional.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Auto-Generated Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title auto-title">
                      <FormattedMessage
                        id="notebook.virology.manifest.autoGeneratedFields"
                        defaultMessage="Auto-Generated Fields (Do not include in CSV)"
                      />
                      <Tag type="green" size="sm">
                        {EXPECTED_DATA_POINTS.autoGenerated.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.field"
                              defaultMessage="Field"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.autoGenerated.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {/* File Upload */}
            <div className="file-upload-section">
              {!file ? (
                <FileUploaderDropContainer
                  accept={[".csv"]}
                  labelText={intl.formatMessage({
                    id: "notebook.virology.manifest.dropzone",
                    defaultMessage:
                      "Drag and drop a CSV file here or click to upload",
                  })}
                  onAddFiles={handleFileAdded}
                />
              ) : (
                <FileUploaderItem
                  name={file.name}
                  status="edit"
                  onDelete={handleRemoveFile}
                />
              )}
            </div>
            {fileError && (
              <InlineNotification
                kind="error"
                title={fileError}
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 2 && (
          <div className="mapping-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.virology.manifest.step2"
                defaultMessage="Map your CSV columns to the expected reception metadata fields. All required fields (marked with *) must be mapped."
              />
            </p>

            {/* Required Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.virology.manifest.requiredMappings"
                  defaultMessage="Required Fields - Sample Arrival"
                />
                <Tag type="red" size="sm">
                  6
                </Tag>
              </h5>
              <div className="mapping-grid">
                <div className="mapping-field required">
                  {mappingField(
                    "sampleIdColumn",
                    "notebook.virology.manifest.column.sampleId",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "sourceColumn",
                    "notebook.virology.manifest.column.source",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "sampleTypeColumn",
                    "notebook.virology.manifest.column.sampleType",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "receptionDateTimeColumn",
                    "notebook.virology.manifest.column.receptionDateTime",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "testTypeColumn",
                    "notebook.virology.manifest.column.testType",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "projectStudyAssociationColumn",
                    "notebook.virology.manifest.column.projectStudyAssociation",
                  )}
                  <span className="required-marker">*</span>
                </div>
              </div>
            </div>

            {/* Virus/Vaccine Production Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.virology.manifest.productionMappings"
                  defaultMessage="Virus/Vaccine Production Fields"
                />
                <Tag type="purple" size="sm">
                  7
                </Tag>
              </h5>
              <p className="mapping-section-info">
                <FormattedMessage
                  id="notebook.virology.manifest.productionInfo"
                  defaultMessage="These fields are relevant for virus culture and vaccine production workflows."
                />
              </p>
              <div className="mapping-grid">
                {mappingField(
                  "batchIdColumn",
                  "notebook.virology.manifest.column.batchId",
                )}
                {mappingField(
                  "productionStageColumn",
                  "notebook.virology.manifest.column.productionStage",
                )}
                {mappingField(
                  "cellLineUsedColumn",
                  "notebook.virology.manifest.column.cellLineUsed",
                )}
                {mappingField(
                  "passageNumberColumn",
                  "notebook.virology.manifest.column.passageNumber",
                )}
                {mappingField(
                  "titerValuesColumn",
                  "notebook.virology.manifest.column.titerValues",
                )}
                {mappingField(
                  "qualityControlResultsColumn",
                  "notebook.virology.manifest.column.qualityControlResults",
                )}
                {mappingField(
                  "formulationDetailsColumn",
                  "notebook.virology.manifest.column.formulationDetails",
                )}
              </div>
            </div>

            {/* Optional Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.virology.manifest.optionalMappings"
                  defaultMessage="Optional Fields"
                />
                <Tag type="blue" size="sm">
                  6
                </Tag>
              </h5>
              <div className="mapping-grid">
                {mappingField(
                  "collectionDateTimeColumn",
                  "notebook.virology.manifest.column.collectionDateTime",
                )}
                {mappingField(
                  "storageConditionOnArrivalColumn",
                  "notebook.virology.manifest.column.storageConditionOnArrival",
                )}
                {mappingField(
                  "transportTemperatureColumn",
                  "notebook.virology.manifest.column.transportTemperature",
                )}
                {mappingField(
                  "receivingPersonnelNameColumn",
                  "notebook.virology.manifest.column.receivingPersonnelName",
                )}
                {mappingField(
                  "manifestVerificationStatusColumn",
                  "notebook.virology.manifest.column.manifestVerificationStatus",
                )}
                {mappingField(
                  "notesColumn",
                  "notebook.virology.manifest.column.notes",
                )}
              </div>
            </div>

            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 3 && (
          <div className="preview-step">
            {isPreviewLoading ? (
              <Loading withOverlay={false} description="Loading preview..." />
            ) : (
              <>
                {previewErrors.length > 0 && (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={
                      <ul className="error-list">
                        {previewErrors.map((error, idx) => (
                          <li key={idx}>
                            {error.rowNumber > 0
                              ? `Row ${error.rowNumber}: `
                              : ""}
                            {error.message}
                          </li>
                        ))}
                      </ul>
                    }
                    lowContrast
                    hideCloseButton
                  />
                )}

                {previewData && previewErrors.length === 0 && (
                  <div className="preview-summary">
                    <Tag type="blue">
                      <FormattedMessage
                        id="notebook.manifest.preview.rows"
                        defaultMessage="{count} rows"
                        values={{ count: previewData.totalRows }}
                      />
                    </Tag>
                    <Tag type="green">
                      <FormattedMessage
                        id="notebook.manifest.preview.samples"
                        defaultMessage="{count} samples to create"
                        values={{ count: previewData.totalSamplesToCreate }}
                      />
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {step === 4 && (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h3>
              <FormattedMessage
                id="notebook.manifest.success.title"
                defaultMessage="Import Successful"
              />
            </h3>
            <p>
              <FormattedMessage
                id="notebook.virology.manifest.success.message"
                defaultMessage="Virology samples have been created and linked to the notebook entry with reception metadata."
              />
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default VirologyManifestImportModal;
