package org.openelisglobal.analyzer.service;

public enum AnalyzerTypeAttentionCode {
    SITE_BINDING_REQUIRED, MULTIPLE_SITE_BINDINGS, PROFILE_REVISION_MISMATCH, MISSING_TEST_ROWS, EXTRA_TEST_ROWS,
    UNRESOLVED_TEST_MAPPINGS, RESULT_VALUE_BINDING_REQUIRED
}
