package org.openelisglobal.environmentalmonitoring.valueholder;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.sql.Timestamp;
import java.util.UUID;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.openelisglobal.common.valueholder.BaseObject;

/**
 * LabEnvironmentalLog - Stores lab-wide environmental monitoring data including
 * temperature logs for various storage units and equipment.
 *
 * This entity replaces the workflow-specific temperature logging with a
 * lab-wide approach that supports different storage unit types with
 * context-specific fields.
 */
@Entity
@Table(name = "lab_environmental_log")
@Getter
@Setter
@AllArgsConstructor
public class LabEnvironmentalLog extends BaseObject<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lab_environmental_log_generator")
    @SequenceGenerator(name = "lab_environmental_log_generator", sequenceName = "lab_environmental_log_seq", allocationSize = 1)
    @Column(name = "id")
    private Long id;

    @Column(name = "fhir_uuid")
    private UUID fhirUuid;

    @Enumerated(EnumType.STRING)
    @Column(name = "storage_unit_type", nullable = false, length = 30)
    @NotNull
    private StorageUnitType storageUnitType;

    @Column(name = "storage_unit_id", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    private String storageUnitId; // Equipment/Device ID or Room identifier

    @Column(name = "interval_type", length = 10)
    @Size(max = 10)
    private String intervalType; // AM or PM for scheduled checks

    @Column(name = "temperature_value", nullable = false)
    @NotNull
    private Double temperatureValue;

    @Column(name = "temperature_unit", length = 5)
    @Size(max = 5)
    private String temperatureUnit; // C or F

    @Column(name = "humidity_value")
    private Double humidityValue; // Optional humidity reading

    @Column(name = "checked_by", length = 255)
    @Size(max = 255)
    private String checkedBy;

    @Column(name = "checked_date_time")
    @NotNull
    private Timestamp checkedDateTime;

    @Column(name = "notes", length = 1000)
    @Size(max = 1000)
    private String notes;

    // Additional fields for Movable Fridge context
    @Column(name = "sample_type", length = 100)
    @Size(max = 100)
    private String sampleType; // When storageUnitType = MOVABLE_FRIDGE

    @Column(name = "project_name", length = 255)
    @Size(max = 255)
    private String projectName; // When storageUnitType = MOVABLE_FRIDGE

    @Column(name = "sample_id", length = 100)
    @Size(max = 100)
    private String sampleId; // When storageUnitType = MOVABLE_FRIDGE

    @Column(name = "additional_details", length = 500)
    @Size(max = 500)
    private String additionalDetails; // Any other relevant sample details

    @Column(name = "logged_by", length = 50)
    @Size(max = 50)
    private String loggedBy;

    @Column(name = "logged_at")
    private Timestamp loggedAt;

    public enum StorageUnitType {
        ROOM,
        FREEZER,
        EQUIPMENT_ANALYZER,
        MOVABLE_FRIDGE
    }

    public LabEnvironmentalLog() {
        this.loggedAt = new Timestamp(System.currentTimeMillis());
        this.checkedDateTime = new Timestamp(System.currentTimeMillis());
    }

    @PrePersist
    public void generateFhirUuid() {
        if (this.fhirUuid == null) {
            this.fhirUuid = UUID.randomUUID();
        }
        // ID will be generated by the service layer using sequence
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }
}