import jsPDF from "jspdf";
import "jspdf-autotable";

var MARGIN = 14;
var PAGE_W = 210;
var PAGE_H = 297;
var CONTENT_W = PAGE_W - MARGIN * 2;
var FOOTER_Y = PAGE_H - 8;

function captureChartImage(ref) {
  if (!ref || !ref.current) return Promise.resolve(null);
  var svgEl = ref.current.querySelector("svg");
  if (!svgEl) return Promise.resolve(null);
  try {
    var svgData = new XMLSerializer().serializeToString(svgEl);
    var svgBlob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
    var url = URL.createObjectURL(svgBlob);
    return new Promise(function(resolve) {
      var img = new Image();
      var rect = svgEl.getBoundingClientRect();
      img.onload = function() {
        var canvas = document.createElement("canvas");
        canvas.width  = rect.width  || 600;
        canvas.height = rect.height || 300;
        var ctx = canvas.getContext("2d");
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0);
        URL.revokeObjectURL(url);
        resolve(canvas.toDataURL("image/png"));
      };
      img.onerror = function() { URL.revokeObjectURL(url); resolve(null); };
      img.src = url;
    });
  } catch (err) {
    return Promise.resolve(null);
  }
}

function addFooter(doc, pageNum, totalPages, labName) {
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(labName, MARGIN, FOOTER_Y);
  doc.text("Page " + pageNum + " of " + totalPages, PAGE_W / 2, FOOTER_Y, { align: "center" });
  doc.text("Generated by OpenELIS Global", PAGE_W - MARGIN, FOOTER_Y, { align: "right" });
  doc.setTextColor(0);
}

function addChartOrPlaceholder(doc, imgData, y, h) {
  if (imgData) {
    doc.addImage(imgData, "PNG", MARGIN, y, CONTENT_W, h);
  } else {
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("[Chart image unavailable]", PAGE_W / 2, y + h / 2, { align: "center" });
    doc.setTextColor(0);
  }
}

export function generateCompliancePdf(data, meta) {
  var summary      = data.summary;
  var trend        = data.trend;
  var siteParams   = data.siteParams;
  var comparison   = data.comparison;
  var exceedances  = data.exceedances;
  var labName      = meta.labName    || "OpenELIS Lab";
  var period       = meta.period     || "";
  var standard     = meta.standard   || "All Standards";
  var preparedBy   = meta.preparedBy || "";
  var trendRef     = meta.trendRef;
  var drilldownRef = meta.drilldownRef;
  var compRef      = meta.comparisonRef;
  var totalPages   = 5;
  var generated    = meta.generatedAt || new Date().toLocaleString();

  return Promise.all([
    captureChartImage(trendRef),
    captureChartImage(drilldownRef),
    captureChartImage(compRef),
  ]).then(function(imgs) {
    var trendImg      = imgs[0];
    var drilldownImg  = imgs[1];
    var comparisonImg = imgs[2];

    var doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    // Page 1 — Cover
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text(labName.toUpperCase(), PAGE_W / 2, 50, { align: "center" });
    doc.setFontSize(20);
    doc.setTextColor(0);
    doc.setFont(undefined, "bold");
    doc.text("Environmental Compliance Dashboard", PAGE_W / 2, 68, { align: "center", maxWidth: CONTENT_W });
    doc.setFont(undefined, "normal");
    doc.setDrawColor(0, 98, 196);
    doc.setLineWidth(0.5);
    doc.line(MARGIN + 20, 74, PAGE_W - MARGIN - 20, 74);
    var fields = [
      ["Period:",      period],
      ["Standard:",    standard],
      ["Prepared by:", preparedBy],
      ["Generated:",   generated],
    ];
    var y = 88;
    doc.setFontSize(11);
    fields.forEach(function(f) {
      doc.setFont(undefined, "bold");
      doc.text(f[0], PAGE_W / 2 - 28, y, { align: "right" });
      doc.setFont(undefined, "normal");
      doc.text(f[1] || "—", PAGE_W / 2 - 22, y);
      y += 10;
    });
    addFooter(doc, 1, totalPages, labName);

    // Page 2 — Trend
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont(undefined, "bold");
    doc.text("Compliance Rate Trend — All Sites", PAGE_W / 2, 20, { align: "center" });
    doc.setFont(undefined, "normal");
    addChartOrPlaceholder(doc, trendImg, 28, 110);
    addFooter(doc, 2, totalPages, labName);

    // Page 3 — Drill-Down
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont(undefined, "bold");
    var drillTitle = (siteParams && siteParams.siteName)
      ? "Site Drill-Down — " + siteParams.siteName + ": Per-Parameter Trend"
      : "Site Drill-Down — Per-Parameter Trend";
    doc.text(drillTitle, PAGE_W / 2, 20, { align: "center", maxWidth: CONTENT_W });
    doc.setFont(undefined, "normal");
    addChartOrPlaceholder(doc, drilldownImg, 28, 110);
    addFooter(doc, 3, totalPages, labName);

    // Page 4 — Comparison
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont(undefined, "bold");
    doc.text("Site Comparison — " + period + " Compliance %", PAGE_W / 2, 20, { align: "center", maxWidth: CONTENT_W });
    doc.setFont(undefined, "normal");
    addChartOrPlaceholder(doc, comparisonImg, 28, 110);
    addFooter(doc, 4, totalPages, labName);

    // Page 5 — Exceedances
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont(undefined, "bold");
    doc.text("Exceedance Summary", PAGE_W / 2, 20, { align: "center" });
    doc.setFont(undefined, "normal");
    var rows = (exceedances && exceedances.items ? exceedances.items : []).map(function(item) {
      return [item.date, item.labNumber, item.parameter, item.result, item.threshold, item.status];
    });
    doc.autoTable({
      startY: 28,
      head: [["Date", "Lab #", "Parameter", "Result", "Threshold", "Status"]],
      body: rows,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [0, 98, 196], textColor: 255 },
      didParseCell: function(d) {
        if (d.section === "body" && d.column.index === 5) {
          if (d.cell.raw === "FAIL")     { d.cell.styles.textColor = [218, 30, 40];  d.cell.styles.fontStyle = "bold"; }
          if (d.cell.raw === "MARGINAL") { d.cell.styles.textColor = [255, 131, 0];  d.cell.styles.fontStyle = "bold"; }
        }
      },
      didDrawPage: function(hookData) {
        var pn = 4 + hookData.pageNumber;
        addFooter(doc, pn, Math.max(totalPages, pn), labName);
      },
    });

    var filename = "compliance-dashboard-" + period.replace(/[^0-9-]/g, "_") + ".pdf";
    doc.save(filename);
  });
}
