name: Publish STAGING images to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-staging:
    uses: ./.github/workflows/publish-ghcr.yml
    with:
      tag: staging
      include_sha_tag: true
      include_latest_tag: false

